import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    "home.welcome": "Bienvenue",
    "home.description": "Ceci est une application de gestion de projets.",
    "projects.title": "Projets",
    "projects.create": "Créer un projet",
    "projects.import": "Importer des projets",
    "projects.detail": "Détail du projet",
    "projects.edit": "Modifier le projet",
    "projects.list": "Liste des projets",
    "projects.no_projects": "Aucun projet trouvé.",
    "projects.name": "Nom du projet",
    "projects.description": "Description du projet",
    "projects.start_date": "Date de début",
    "projects.end_date": "Date de fin",
    "projects.status": "Statut",
    "projects.actions": "Actions",
    "projects.create_success": "Projet créé avec succès!",
    "projects.update_success": "Projet mis à jour avec succès!",
    "projects.delete_success": "Projet supprimé avec succès!",
    "projects.import_success": "Projets importés avec succès!",
    "projects.import_error": "Erreur lors de l'importation des projets.",
    "projects.delete_confirm": "Êtes-vous sûr de vouloir supprimer ce projet?",
    "projects.status_new": "Nouveau",
    "projects.status_in_progress": "En cours",
    "projects.status_completed": "Terminé",
    "projects.status_on_hold": "En attente",
    "projects.status_cancelled": "Annulé",
    "projects.status_planning": "Planification",
    "projects.status_pending": "En attente",
    "projects.status_suspended": "Suspendu",
    "projects.priority_urgent": "Urgent",
    "projects.priority_high": "Élevé",
    "projects.priority_medium": "Moyen",
    "projects.priority_low": "Faible",
    "materials.title": "Matériaux",
    "materials.create": "Créer un matériau",
    "materials.detail": "Détail du matériau",
    "materials.edit": "Modifier le matériau",
    "materials.list": "Liste des matériaux",
    "materials.no_materials": "Aucun matériau trouvé.",
    "materials.name": "Nom du matériau",
    "materials.description": "Description du matériau",
    "materials.quantity": "Quantité",
    "materials.unit": "Unité",
    "materials.price": "Prix",
    "materials.create_success": "Matériau créé avec succès!",
    "materials.update_success": "Matériau mis à jour avec succès!",
    "materials.delete_success": "Matériau supprimé avec succès!",
    "materials.delete_confirm": "Êtes-vous sûr de vouloir supprimer ce matériau?",
    "materials.available_quantity": "Quantité disponible",
    "materials.min_quantity": "Quantité minimale",
    "materials.supplier": "Fournisseur",
    "materials.restock_date": "Date de réapprovisionnement",
    "documents.title": "Documents",
    "documents.upload": "Télécharger document",
    "documents.type_contract": "Contrat",
    "documents.type_report": "Rapport",
    "documents.type_invoice": "Facture",
    "documents.type_inspection": "Inspection",
    "documents.type_permit": "Permis",
    "documents.type_customs": "Douanes",
    "documents.format_photo": "Photo",
    "documents.format_pdf": "PDF",
    "documents.format_doc": "Document Word",
    "documents.format_excel": "Excel",
    "documents.format_customs_form": "Formulaire douanier",
    "tasks.title": "Tâches",
    "tasks.status_todo": "À faire",
    "tasks.status_blocked": "Bloqué",
    "tasks.status_in_progress": "En cours",
    "tasks.status_done": "Terminé",
    "users.title": "Utilisateurs",
    "users.list": "Liste des utilisateurs",
    "users.no_users": "Aucun utilisateur trouvé.",
    "users.name": "Nom",
    "users.email": "Email",
    "users.role": "Rôle",
    "users.actions": "Actions",
    "users.role_admin": "Administrateur",
    "users.role_manager": "Manager",
    "users.role_field_agent": "Agent terrain",
    "users.role_inspector": "Inspecteur",
    "users.role_viewer": "Observateur",
    "dashboard.title": "Tableau de bord",
    "settings.title": "Paramètres",
    "auth.login": "Se connecter",
    "auth.register": "S'inscrire",
    "auth.logout": "Se déconnecter",
    "auth.email": "Adresse email",
    "auth.password": "Mot de passe",
    "auth.name": "Nom",
    "auth.login_success": "Connexion réussie!",
    "auth.login_error": "Erreur de connexion.",
    "auth.register_success": "Inscription réussie!",
    "auth.register_error": "Erreur d'inscription.",
    "profile.title": "Profil",
    "profile.update_success": "Profil mis à jour avec succès!",
    "contact.title": "Contact",
    "contact.description": "Contactez-nous si vous avez des questions.",
    "contact.name": "Nom",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.send": "Envoyer",
    "contact.success": "Message envoyé avec succès!",
    "contact.error": "Erreur lors de l'envoi du message.",
    "terms.title": "Conditions d'utilisation",
    "policy.title": "Politique de confidentialité",
    "not_found.title": "Page non trouvée",
    "not_found.description": "La page que vous recherchez n'existe pas.",
    "global.save": "Enregistrer",
    "global.cancel": "Annuler",
    "global.edit": "Modifier",
    "global.delete": "Supprimer",
    "global.create": "Créer",
    "global.import": "Importer",
    "global.export": "Exporter",
    "global.search": "Rechercher",
    "global.loading": "Chargement...",
    "global.confirm": "Confirmer",
    "global.error": "Erreur",
    "global.success": "Succès",
    "global.validation_error": "Erreur de validation",
    "global.required": "Ce champ est obligatoire.",
    "global.date_format": "dd/MM/yyyy",
    "role_based_route.loading": "Chargement...",
    "role_based_route.denied_title": "Accès refusé",
    "role_based_route.denied_desc": "Vous n'avez pas les autorisations nécessaires pour accéder à cette page.",
    "role_based_route.required_roles": "Rôles requis",
    "role_based_route.back": "Retour",
    "nav.tender_management": "Appels d'Offres",
    "nav.projects": "Projets",
    "nav.materials": "Matériaux",
    "nav.users": "Utilisateurs",
    "nav.login": "Se connecter",
    "language.french": "Français",
    "language.arabic": "العربية",
    "language.english": "English",
    // Locations - Mauritania
    "location.nouakchott": "Nouakchott",
    "location.nouadhibou": "Nouadhibou",
    "location.adrar": "Adrar",
    "location.assaba": "Assaba",
    "location.brakna": "Brakna",
    "location.dakhlet_nouadhibou": "Dakhlet Nouadhibou",
    "location.gorgol": "Gorgol",
    "location.guidimaka": "Guidimaka",
    "location.hodh_ech_chargui": "Hodh Ech Chargui",
    "location.hodh_el_gharbi": "Hodh El Gharbi",
    "location.inchiri": "Inchiri",
    "location.tagant": "Tagant",
    "location.tiris_zemmour": "Tiris Zemmour",
    "location.trarza": "Trarza",
    "location.other": "Autre",
    // Workspaces
    "workspace.title": "Espaces de travail",
    "workspace.create": "Créer un espace",
    "workspace.name": "Nom de l'espace",
    "workspace.location": "Localisation",
    "workspace.status": "Statut",
    "workspace.status_active": "Actif",
    "workspace.status_inactive": "Inactif",
    "workspace.status_closed": "Fermé",
    "workspace.facilities": "Installations",
    "workspace.manager": "Responsable",
    "workspace.phone": "Téléphone",
    // Payments
    "payment.title": "Paiements",
    "payment.amount": "Montant",
    "payment.date": "Date",
    "payment.method": "Méthode",
    "payment.method_cash": "Espèces",
    "payment.method_bank": "Banque",
    "payment.method_mobile_money": "Mobile Money",
    "payment.method_hawala": "Hawala",
    "payment.reference": "Référence",
    "payment.recipient": "Bénéficiaire",
    "payment.verified_by": "Vérifié par",
    "payment.notes": "Notes",
    "payment.progress": "Progression au paiement",
    // Inspections
    "inspection.title": "Inspections",
    "inspection.date": "Date d'inspection",
    "inspection.status": "Statut",
    "inspection.status_approved": "Approuvé",
    "inspection.status_requires_changes": "Modifications requises",
    "inspection.status_rejected": "Rejeté",
    "inspection.status_pending": "En attente",
    "inspection.inspector": "Inspecteur",
    "inspection.agency": "Agence",
    "inspection.comments": "Commentaires",
    "inspection.progress": "Progression à l'inspection",
    // Tender Workflow Steps
    "tenders.steps.title": "Étapes du Processus d'Appel d'Offres",
    "tenders.steps.add": "Ajouter Étape",
    "tenders.steps.add_document": "Ajouter Document",
    "tenders.steps.step_number": "Numéro d'étape",
    "tenders.steps.title_field": "Titre",
    "tenders.steps.description": "Description",
    "tenders.steps.due_date": "Date d'échéance",
    "tenders.steps.required_documents": "Documents requis",
    "tenders.steps.status_pending": "En attente",
    "tenders.steps.status_in_progress": "En cours",
    "tenders.steps.status_completed": "Terminée",
    "tenders.steps.status_approved": "Approuvée",
    "tenders.steps.document_type": "Type de document",
    "tenders.steps.document_title": "Titre du document",
    "tenders.steps.document_required": "Document requis",
    "tenders.steps.document_status_pending": "En attente",
    "tenders.steps.document_status_submitted": "Soumis",
    "tenders.steps.document_status_approved": "Approuvé",
    "tenders.steps.document_status_rejected": "Rejeté",
    "tenders.steps.file": "Fichier",
    "tenders.steps.reviewer_notes": "Notes du réviseur",
    "tenders.steps.view": "Voir",
    "tenders.steps.no_steps": "Aucune étape définie pour cet appel d'offres.",
    "tenders.steps.add_first": "Ajouter la première étape",
    "tenders.steps.select_tender": "Sélectionnez un appel d'offres",
    "tenders.steps.select_tender_desc": "Choisissez un appel d'offres dans l'onglet précédent pour gérer ses étapes.",
    "tenders.steps.add_success": "Étape ajoutée avec succès",
    "tenders.steps.add_error": "Erreur lors de l'ajout de l'étape",
    "tenders.steps.document_add_success": "Document ajouté avec succès",
    "tenders.steps.document_add_error": "Erreur lors de l'ajout du document",
    "tenders.steps.upload_progress": "Téléchargement...",
    "tenders.steps.select_file_error": "Veuillez sélectionner un fichier et une étape."
  },
  ar: {
    "home.welcome": "مرحبا",
    "home.description": "هذا تطبيق لإدارة المشاريع.",
    "projects.title": "المشاريع",
    "projects.create": "إنشاء مشروع",
    "projects.import": "استيراد مشاريع",
    "projects.detail": "تفاصيل المشروع",
    "projects.edit": "تعديل المشروع",
    "projects.list": "قائمة المشاريع",
    "projects.no_projects": "لا توجد مشاريع.",
    "projects.name": "اسم المشروع",
    "projects.description": "وصف المشروع",
    "projects.start_date": "تاريخ البدء",
    "projects.end_date": "تاريخ الانتهاء",
    "projects.status": "الحالة",
    "projects.actions": "الإجراءات",
    "projects.create_success": "تم إنشاء المشروع بنجاح!",
    "projects.update_success": "تم تحديث المشروع بنجاح!",
    "projects.delete_success": "تم حذف المشروع بنجاح!",
    "projects.import_success": "تم استيراد المشاريع بنجاح!",
    "projects.import_error": "خطأ في استيراد المشاريع.",
    "projects.delete_confirm": "هل أنت متأكد أنك تريد حذف هذا المشروع؟",
    "projects.status_new": "جديد",
    "projects.status_in_progress": "قيد التقدم",
    "projects.status_completed": "مكتمل",
    "projects.status_on_hold": "معلق",
    "projects.status_cancelled": "ملغي",
    "projects.status_planning": "تخطيط",
    "projects.status_pending": "معلق",
    "projects.status_suspended": "متوقف",
    "projects.priority_urgent": "عاجل",
    "projects.priority_high": "عالي",
    "projects.priority_medium": "متوسط",
    "projects.priority_low": "منخفض",
    "materials.title": "المواد",
    "materials.create": "إنشاء مادة",
    "materials.detail": "تفاصيل المادة",
    "materials.edit": "تعديل المادة",
    "materials.list": "قائمة المواد",
    "materials.no_materials": "لا توجد مواد.",
    "materials.name": "اسم المادة",
    "materials.description": "وصف المادة",
    "materials.quantity": "الكمية",
    "materials.unit": "الوحدة",
    "materials.price": "السعر",
    "materials.create_success": "تم إنشاء المادة بنجاح!",
    "materials.update_success": "تم تحديث المادة بنجاح!",
    "materials.delete_success": "تم حذف المادة بنجاح!",
    "materials.delete_confirm": "هل أنت متأكد أنك تريد حذف هذه المادة؟",
    "materials.available_quantity": "الكمية المتاحة",
    "materials.min_quantity": "الحد الأدنى للكمية",
    "materials.supplier": "المورد",
    "materials.restock_date": "تاريخ إعادة التخزين",
    "documents.title": "المستندات",
    "documents.upload": "رفع مستند",
    "documents.type_contract": "عقد",
    "documents.type_report": "تقرير",
    "documents.type_invoice": "فاتورة",
    "documents.type_inspection": "تفتيش",
    "documents.type_permit": "تصريح",
    "documents.type_customs": "جمارك",
    "documents.format_photo": "صورة",
    "documents.format_pdf": "PDF",
    "documents.format_doc": "مستند Word",
    "documents.format_excel": "Excel",
    "documents.format_customs_form": "نموذج جمركي",
    "tasks.title": "المهام",
    "tasks.status_todo": "للقيام",
    "tasks.status_blocked": "محظور",
    "tasks.status_in_progress": "قيد التقدم",
    "tasks.status_done": "مكتمل",
    "users.title": "المستخدمون",
    "users.list": "قائمة المستخدمين",
    "users.no_users": "لا يوجد مستخدمون.",
    "users.name": "الاسم",
    "users.email": "البريد الإلكتروني",
    "users.role": "الدور",
    "users.actions": "الإجراءات",
    "users.role_admin": "مدير",
    "users.role_manager": "مدير",
    "users.role_field_agent": "وكيل ميداني",
    "users.role_inspector": "مفتش",
    "users.role_viewer": "مشاهد",
    "dashboard.title": "لوحة التحكم",
    "settings.title": "الإعدادات",
    "auth.login": "تسجيل الدخول",
    "auth.register": "تسجيل",
    "auth.logout": "تسجيل الخروج",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.name": "الاسم",
    "auth.login_success": "تم تسجيل الدخول بنجاح!",
    "auth.login_error": "خطأ في تسجيل الدخول.",
    "auth.register_success": "تم التسجيل بنجاح!",
    "auth.register_error": "خطأ في التسجيل.",
    "profile.title": "الملف الشخصي",
    "profile.update_success": "تم تحديث الملف الشخصي بنجاح!",
    "contact.title": "اتصل بنا",
    "contact.description": "اتصل بنا إذا كان لديك أي أسئلة.",
    "contact.name": "الاسم",
    "contact.email": "البريد الإلكتروني",
    "contact.message": "الرسالة",
    "contact.send": "إرسال",
    "contact.success": "تم إرسال الرسالة بنجاح!",
    "contact.error": "خطأ في إرسال الرسالة.",
    "terms.title": "شروط الاستخدام",
    "policy.title": "سياسة الخصوصية",
    "not_found.title": "الصفحة غير موجودة",
    "not_found.description": "الصفحة التي تبحث عنها غير موجودة.",
    "global.save": "حفظ",
    "global.cancel": "إلغاء",
    "global.edit": "تعديل",
    "global.delete": "حذف",
    "global.create": "إنشاء",
    "global.import": "استيراد",
    "global.export": "تصدير",
    "global.search": "بحث",
    "global.loading": "جاري التحميل...",
    "global.confirm": "تأكيد",
    "global.error": "خطأ",
    "global.success": "نجاح",
    "global.validation_error": "خطأ في التحقق",
    "global.required": "هذا الحقل مطلوب.",
    "global.date_format": "يوم/شهر/سنة",
    "role_based_route.loading": "جاري التحميل...",
    "role_based_route.denied_title": "تم رفض الوصول",
    "role_based_route.denied_desc": "ليس لديك الصلاحيات اللازمة للوصول إلى هذه الصفحة.",
    "role_based_route.required_roles": "الأدوار المطلوبة",
    "role_based_route.back": "العودة",
    "nav.tender_management": "المناقصات",
    "nav.projects": "المشاريع",
    "nav.materials": "المواد",
    "nav.users": "المستخدمون",
    "nav.login": "تسجيل الدخول",
    "language.french": "Français",
    "language.arabic": "العربية",
    "language.english": "English",
    // Locations - Mauritania
    "location.nouakchott": "نواكشوط",
    "location.nouadhibou": "نواذيبو",
    "location.adrar": "آدرار",
    "location.assaba": "العصابة",
    "location.brakna": "براكنة",
    "location.dakhlet_nouadhibou": "داخلة نواذيبو",
    "location.gorgol": "كوركول",
    "location.guidimaka": "غيديماغا",
    "location.hodh_ech_chargui": "الحوض الشرقي",
    "location.hodh_el_gharbi": "الحوض الغربي",
    "location.inchiri": "إينشيري",
    "location.tagant": "تكانت",
    "location.tiris_zemmour": "تيرس زمور",
    "location.trarza": "ترارزة",
    "location.other": "أخرى",
    // Workspaces
    "workspace.title": "مساحات العمل",
    "workspace.create": "إنشاء مساحة",
    "workspace.name": "اسم المساحة",
    "workspace.location": "الموقع",
    "workspace.status": "الحالة",
    "workspace.status_active": "نشط",
    "workspace.status_inactive": "غير نشط",
    "workspace.status_closed": "مغلق",
    "workspace.facilities": "المرافق",
    "workspace.manager": "المدير",
    "workspace.phone": "الهاتف",
    // Payments
    "payment.title": "المدفوعات",
    "payment.amount": "المبلغ",
    "payment.date": "التاريخ",
    "payment.method": "الطريقة",
    "payment.method_cash": "نقداً",
    "payment.method_bank": "بنك",
    "payment.method_mobile_money": "المال المحمول",
    "payment.method_hawala": "حوالة",
    "payment.reference": "المرجع",
    "payment.recipient": "المستفيد",
    "payment.verified_by": "تم التحقق بواسطة",
    "payment.notes": "ملاحظات",
    "payment.progress": "التقدم في الدفع",
    // Inspections
    "inspection.title": "التفتيشات",
    "inspection.date": "تاريخ التفتيش",
    "inspection.status": "الحالة",
    "inspection.status_approved": "معتمد",
    "inspection.status_requires_changes": "يتطلب تغييرات",
    "inspection.status_rejected": "مرفوض",
    "inspection.status_pending": "معلق",
    "inspection.inspector": "المفتش",
    "inspection.agency": "الوكالة",
    "inspection.comments": "التعليقات",
    "inspection.progress": "التقدم في التفتيش",
    // Tender Workflow Steps
    "tenders.steps.title": "خطوات عملية المناقصة",
    "tenders.steps.add": "إضافة خطوة",
    "tenders.steps.add_document": "إضافة مستند",
    "tenders.steps.step_number": "رقم الخطوة",
    "tenders.steps.title_field": "العنوان",
    "tenders.steps.description": "الوصف",
    "tenders.steps.due_date": "تاريخ الاستحقاق",
    "tenders.steps.required_documents": "المستندات المطلوبة",
    "tenders.steps.status_pending": "معلق",
    "tenders.steps.status_in_progress": "قيد التقدم",
    "tenders.steps.status_completed": "مكتمل",
    "tenders.steps.status_approved": "معتمد",
    "tenders.steps.document_type": "نوع المستند",
    "tenders.steps.document_title": "عنوان المستند",
    "tenders.steps.document_required": "مستند مطلوب",
    "tenders.steps.document_status_pending": "معلق",
    "tenders.steps.document_status_submitted": "مقدم",
    "tenders.steps.document_status_approved": "معتمد",
    "tenders.steps.document_status_rejected": "مرفوض",
    "tenders.steps.file": "الملف",
    "tenders.steps.reviewer_notes": "ملاحظات المراجع",
    "tenders.steps.view": "عرض",
    "tenders.steps.no_steps": "لا توجد خطوات محددة لهذه المناقصة.",
    "tenders.steps.add_first": "إضافة الخطوة الأولى",
    "tenders.steps.select_tender": "اختر مناقصة",
    "tenders.steps.select_tender_desc": "اختر مناقصة من التبويب السابق لإدارة خطواتها.",
    "tenders.steps.add_success": "تم إضافة الخطوة بنجاح",
    "tenders.steps.add_error": "خطأ في إضافة الخطوة",
    "tenders.steps.document_add_success": "تم إضافة المستند بنجاح",
    "tenders.steps.document_add_error": "خطأ في إضافة المستند",
    "tenders.steps.upload_progress": "جاري الرفع...",
    "tenders.steps.select_file_error": "يرجى تحديد ملف وخطوة."
  },
  en: {
    "home.welcome": "Welcome",
    "home.description": "This is a project management application.",
    "projects.title": "Projects",
    "projects.create": "Create Project",
    "projects.import": "Import Projects",
    "projects.detail": "Project Detail",
    "projects.edit": "Edit Project",
    "projects.list": "Project List",
    "projects.no_projects": "No projects found.",
    "projects.name": "Project Name",
    "projects.description": "Project Description",
    "projects.start_date": "Start Date",
    "projects.end_date": "End Date",
    "projects.status": "Status",
    "projects.actions": "Actions",
    "projects.create_success": "Project created successfully!",
    "projects.update_success": "Project updated successfully!",
    "projects.delete_success": "Project deleted successfully!",
    "projects.import_success": "Projects imported successfully!",
    "projects.import_error": "Error importing projects.",
    "projects.delete_confirm": "Are you sure you want to delete this project?",
    "projects.status_new": "New",
    "projects.status_in_progress": "In Progress",
    "projects.status_completed": "Completed",
    "projects.status_on_hold": "On Hold",
    "projects.status_cancelled": "Cancelled",
    "projects.status_planning": "Planning",
    "projects.status_pending": "Pending",
    "projects.status_suspended": "Suspended",
    "projects.priority_urgent": "Urgent",
    "projects.priority_high": "High",
    "projects.priority_medium": "Medium",
    "projects.priority_low": "Low",
    "materials.title": "Materials",
    "materials.create": "Create Material",
    "materials.detail": "Material Detail",
    "materials.edit": "Edit Material",
    "materials.list": "Material List",
    "materials.no_materials": "No materials found.",
    "materials.name": "Material Name",
    "materials.description": "Material Description",
    "materials.quantity": "Quantity",
    "materials.unit": "Unit",
    "materials.price": "Price",
    "materials.create_success": "Material created successfully!",
    "materials.update_success": "Material updated successfully!",
    "materials.delete_success": "Material deleted successfully!",
    "materials.delete_confirm": "Are you sure you want to delete this material?",
    "materials.available_quantity": "Available Quantity",
    "materials.min_quantity": "Minimum Quantity",
    "materials.supplier": "Supplier",
    "materials.restock_date": "Restock Date",
    "documents.title": "Documents",
    "documents.upload": "Upload Document",
    "documents.type_contract": "Contract",
    "documents.type_report": "Report",
    "documents.type_invoice": "Invoice",
    "documents.type_inspection": "Inspection",
    "documents.type_permit": "Permit",
    "documents.type_customs": "Customs",
    "documents.format_photo": "Photo",
    "documents.format_pdf": "PDF",
    "documents.format_doc": "Word Document",
    "documents.format_excel": "Excel",
    "documents.format_customs_form": "Customs Form",
    "tasks.title": "Tasks",
    "tasks.status_todo": "To Do",
    "tasks.status_blocked": "Blocked",
    "tasks.status_in_progress": "In Progress",
    "tasks.status_done": "Done",
    "users.title": "Users",
    "users.list": "User List",
    "users.no_users": "No users found.",
    "users.name": "Name",
    "users.email": "Email",
    "users.role": "Role",
    "users.actions": "Actions",
    "users.role_admin": "Admin",
    "users.role_manager": "Manager",
    "users.role_field_agent": "Field Agent",
    "users.role_inspector": "Inspector",
    "users.role_viewer": "Viewer",
    "dashboard.title": "Dashboard",
    "settings.title": "Settings",
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.logout": "Logout",
    "auth.email": "Email Address",
    "auth.password": "Password",
    "auth.name": "Name",
    "auth.login_success": "Login successful!",
    "auth.login_error": "Login error.",
    "auth.register_success": "Registration successful!",
    "auth.register_error": "Registration error.",
    "profile.title": "Profile",
    "profile.update_success": "Profile updated successfully!",
    "contact.title": "Contact",
    "contact.description": "Contact us if you have any questions.",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.send": "Send",
    "contact.success": "Message sent successfully!",
    "contact.error": "Error sending message.",
    "terms.title": "Terms of Service",
    "policy.title": "Privacy Policy",
    "not_found.title": "Page Not Found",
    "not_found.description": "The page you are looking for does not exist.",
    "global.save": "Save",
    "global.cancel": "Cancel",
    "global.edit": "Edit",
    "global.delete": "Delete",
    "global.create": "Create",
    "global.import": "Import",
    "global.export": "Export",
    "global.search": "Search",
    "global.loading": "Loading...",
    "global.confirm": "Confirm",
    "global.error": "Error",
    "global.success": "Success",
    "global.validation_error": "Validation Error",
    "global.required": "This field is required.",
    "global.date_format": "MM/dd/yyyy",
    "role_based_route.loading": "Loading...",
    "role_based_route.denied_title": "Access Denied",
    "role_based_route.denied_desc": "You don't have the necessary permissions to access this page.",
    "role_based_route.required_roles": "Required roles",
    "role_based_route.back": "Back",
    "nav.tender_management": "Tender Management",
    "nav.projects": "Projects",
    "nav.materials": "Materials",
    "nav.users": "Users",
    "nav.login": "Login",
    "language.french": "Français",
    "language.arabic": "العربية",
    "language.english": "English",
    // Locations - Mauritania
    "location.nouakchott": "Nouakchott",
    "location.nouadhibou": "Nouadhibou",
    "location.adrar": "Adrar",
    "location.assaba": "Assaba",
    "location.brakna": "Brakna",
    "location.dakhlet_nouadhibou": "Dakhlet Nouadhibou",
    "location.gorgol": "Gorgol",
    "location.guidimaka": "Guidimaka",
    "location.hodh_ech_chargui": "Hodh Ech Chargui",
    "location.hodh_el_gharbi": "Hodh El Gharbi",
    "location.inchiri": "Inchiri",
    "location.tagant": "Tagant",
    "location.tiris_zemmour": "Tiris Zemmour",
    "location.trarza": "Trarza",
    "location.other": "Other",
    // Workspaces
    "workspace.title": "Workspaces",
    "workspace.create": "Create Workspace",
    "workspace.name": "Workspace Name",
    "workspace.location": "Location",
    "workspace.status": "Status",
    "workspace.status_active": "Active",
    "workspace.status_inactive": "Inactive",
    "workspace.status_closed": "Closed",
    "workspace.facilities": "Facilities",
    "workspace.manager": "Manager",
    "workspace.phone": "Phone",
    // Payments
    "payment.title": "Payments",
    "payment.amount": "Amount",
    "payment.date": "Date",
    "payment.method": "Method",
    "payment.method_cash": "Cash",
    "payment.method_bank": "Bank",
    "payment.method_mobile_money": "Mobile Money",
    "payment.method_hawala": "Hawala",
    "payment.reference": "Reference",
    "payment.recipient": "Recipient",
    "payment.verified_by": "Verified By",
    "payment.notes": "Notes",
    "payment.progress": "Progress at Payment",
    // Inspections
    "inspection.title": "Inspections",
    "inspection.date": "Inspection Date",
    "inspection.status": "Status",
    "inspection.status_approved": "Approved",
    "inspection.status_requires_changes": "Requires Changes",
    "inspection.status_rejected": "Rejected",
    "inspection.status_pending": "Pending",
    "inspection.inspector": "Inspector",
    "inspection.agency": "Agency",
    "inspection.comments": "Comments",
    "inspection.progress": "Progress at Inspection",
    // Tender Workflow Steps
    "tenders.steps.title": "Tender Process Steps",
    "tenders.steps.add": "Add Step",
    "tenders.steps.add_document": "Add Document",
    "tenders.steps.step_number": "Step Number",
    "tenders.steps.title_field": "Title",
    "tenders.steps.description": "Description",
    "tenders.steps.due_date": "Due Date",
    "tenders.steps.required_documents": "Required Documents",
    "tenders.steps.status_pending": "Pending",
    "tenders.steps.status_in_progress": "In Progress",
    "tenders.steps.status_completed": "Completed",
    "tenders.steps.status_approved": "Approved",
    "tenders.steps.document_type": "Document Type",
    "tenders.steps.document_title": "Document Title",
    "tenders.steps.document_required": "Required Document",
    "tenders.steps.document_status_pending": "Pending",
    "tenders.steps.document_status_submitted": "Submitted",
    "tenders.steps.document_status_approved": "Approved",
    "tenders.steps.document_status_rejected": "Rejected",
    "tenders.steps.file": "File",
    "tenders.steps.reviewer_notes": "Reviewer Notes",
    "tenders.steps.view": "View",
    "tenders.steps.no_steps": "No steps defined for this tender.",
    "tenders.steps.add_first": "Add the first step",
    "tenders.steps.select_tender": "Select a tender",
    "tenders.steps.select_tender_desc": "Choose a tender from the previous tab to manage its steps.",
    "tenders.steps.add_success": "Step added successfully",
    "tenders.steps.add_error": "Error adding step",
    "tenders.steps.document_add_success": "Document added successfully",
    "tenders.steps.document_add_error": "Error adding document",
    "tenders.steps.upload_progress": "Uploading...",
    "tenders.steps.select_file_error": "Please select a file and a step."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
