import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Complete translations object with all keys for all languages
const translations: Record<Language, Record<string, string>> = {
  fr: {
    'project_import.title': 'Import projet',
    'language.french': "Français",
    'language.english': "Anglais",
    'language.arabic': "Arabe",
    'app.name': 'Gestion de Projets',
    'app.description': 'Système de gestion des projets et matériaux',
    'nav.home': 'Accueil',
    'nav.projects': 'Projets',
    'nav.materials': 'Matériaux',
    'nav.users': 'Utilisateurs',
    'nav.login': 'Connexion',
    'nav.profile': 'Profil',
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.remember_me': 'Se souvenir de moi',
    'auth.forgot_password': 'Mot de passe oublié?',
    'auth.full_name': 'Nom complet',
    'auth.phone': 'Téléphone',
    'auth.national_id': "Identifiant national",
    'auth.accept_terms': "J'accepte les conditions d'utilisation et la politique de confidentialité",
    'auth.submit': 'Soumettre',
    'auth.sign_in_with_google': 'Continuer avec Google',
    'auth.sign_in_with_phone': 'Par téléphone',
    'auth.sign_in_with_national_id': 'Par NIR ID',
    'auth.or_continue_with': 'Ou continuer avec',
    'auth.or_register_with': "Ou s'inscrire avec",
    'auth.create_account': 'Créer un compte',
    'auth.welcome': 'Bienvenue',
    'auth.connect_to_continue': 'Connectez-vous à votre compte pour continuer',
    'auth.simulated_registration': "Inscription simulée",
    'auth.simulated_registration_description': "Ceci est une inscription simulée en mode développement.",
    'auth.simulated_login': "Connexion simulée",
    'auth.reset_password': "Mot de passe oublié?",
    'auth.send_code': "Recevoir un code",
    'auth.verify_code': "Vérifier le code",
    'auth.use_other_phone': "Utiliser un autre numéro de téléphone",
    'auth.use_email_login': "Retour à la connexion par email",
    'auth.use_national_id_login': "Connexion avec NIR ID",
    'auth.password_requirements': "Le mot de passe doit contenir au moins 8 caractères",
    'auth.terms': "conditions d'utilisation",
    'auth.privacy': "politique de confidentialité",
    'auth.error.invalid_credentials': "L'adresse email ou le mot de passe que vous avez saisi est incorrect. Veuillez vérifier et réessayer.",
    'auth.button.loading': 'Chargement...',
    'auth.signup_disabled': "Inscription désactivée",
    'auth.signup_disabled_description': "L'inscription est actuellement désactivée.",
    'auth.weak_password': "Mot de passe faible",
    'auth.weak_password_description': "Votre mot de passe ne répond pas aux exigences de sécurité.",
    'auth.authentication_error': "Erreur d'authentification",
    'auth.unexpected_error': "Une erreur inattendue est survenue.",
    'auth.logout': "Déconnexion",
    'auth.menu': "Menu",
    // Roles
    'roles.admin': 'Administrateur',
    'roles.manager': 'Chef de Projet',
    'roles.director': 'Directeur',
    'roles.agent': 'Agent',
    'roles.supplier': 'Fournisseur',
    'roles.user': 'Utilisateur',
    'roles.assigned': "Rôle attribué",
    'roles.assigned_success': "Le rôle {role} a été attribué avec succès.",
    'roles.assign_error': "Impossible d'attribuer le rôle.",
    'roles.removed': "Rôle retiré",
    'roles.removed_success': "Le rôle {role} a été retiré avec succès.",
    'roles.remove_error': "Impossible de retirer le rôle.",
    // Project Status ENUM
    'project_status.in_progress': 'En cours',
    'project_status.completed': 'Terminé',
    'project_status.pending': 'En attente',
    'project_status.cancelled': 'Annulé',
    // Document Status ENUM
    'document_status.draft': 'Brouillon',
    'document_status.pending_review': 'En attente de révision',
    'document_status.approved': 'Approuvé',
    'document_status.rejected': 'Rejeté',
    'document_status.archived': 'Archivé',
    // Inputs & Descriptions
    'projects.tab.list' :'Projects',
    'projects.title': 'Projets',
    'projects.new': 'Nouveau Projet',
    'projects.search': 'Rechercher un projet...',
    'projects.status.all': 'Tous',
    'projects.empty': 'Aucun projet trouvé',
    'projects.loading_detail': 'Chargement des détails du projet...',
    'projects.not_found': 'Projet non trouvé',
    'projects.not_found_desc': "Le projet que vous recherchez n'existe pas ou a été supprimé.",
    'projects.delete_confirm': 'Êtes-vous sûr de vouloir supprimer le projet "{title}" ?',
    'projects.deleted': 'Projet supprimé',
    'projects.deleted_desc': 'Le projet "{title}" a été supprimé avec succès.',
    'projects.delete_error': 'Erreur',
    'projects.delete_error_desc': 'Impossible de supprimer le projet.',
    'projects.payments_management': 'Gestion des paiements',
    'projects.quick_payment_actions': 'Actions rapides pour effectuer un paiement',
    'projects.progress_done': 'terminé',
    'projects.tab.overview': 'Aperçu',
    'projects.tab.materials': 'Matériaux',
    'projects.tab.payments': 'Paiements',
    'projects.tab.inspections': 'Inspections',
    'projects.tab.workflow': 'Workflow',
    'projects.tab.documents': 'Documents',
    'projects.tab.takeoffs': 'Métrés',
    'projects.tab.map': 'Carte',
    'projects.overview.description': 'Description du projet',
    'projects.timeline': 'Calendrier du projet',
    'projects.start_date': 'Date de début',
    'projects.started': 'Commencé',
    'projects.end_date_expected': 'Date de fin prévue',
    'projects.completed': 'Terminé',
    'projects.expected': 'Prévu',
    'projects.location': 'Localisation',
    'projects.edit.error': "Erreur",
    'projects.edit.not_found': "Projet non trouvé",
    'projects.edit.load_error': "Impossible de charger les détails du projet",
    'projects.edit.saved': "Modifications enregistrées",
    'projects.edit.saved_desc': "Le projet a été mis à jour avec succès",
    'projects.edit.save_error': "Impossible de mettre à jour le projet",
    'projects.edit.back_to_detail': "Retour aux détails du projet",
    'projects.edit.title': "Modifier le projet",
    'projects.edit.subtitle': "Modifiez les détails du projet et enregistrez les changements",
    'projects.edit.status_desc': "Modifier le statut du projet selon son état actuel",
    'projects.edit.sync_with_inspection': "Sync avec inspection",
    'projects.edit.progress_synced': "Progression mise à jour",
    'projects.edit.progress_synced_desc': "Progression définie à {value}% selon la dernière inspection",
    'projects.edit.info': "Information",
    'projects.edit.no_inspection': "Aucune inspection trouvée pour ce projet",
    'projects.edit.inspection_error': "Impossible de récupérer la dernière inspection",
    'projects.edit.end_date': "Date de fin (optionnelle)",
    'projects.edit.saving': "Enregistrement...",
    'projects.edit.save': "Enregistrer les modifications",
    'projects.loading': "Chargement des projets...",
    'projects.map.empty_title': "Aucun projet géolocalisé",
    'projects.map.empty_desc': "Aucun projet avec des coordonnées géographiques n'a été trouvé.",
    'projects.header.title': "Projets",
    'projects.header.subtitle': "Gérez et suivez tous vos projets de construction",
    'projects.header.add': "Ajouter un projet",
    'materials.title': 'Matériaux',
    'materials.new': 'Nouveau Matériau',
    'materials.name': 'Nom',
    'materials.category': 'Catégorie',
    'materials.price': 'Prix unitaire',
    'materials.quantity': 'Quantité',
    'materials.unit': 'Unité',
    'materials.description': 'Description',
    'materials.address': 'Adresse',
    'materials.button.save': 'Enregistrer le matériau',
    'materials.button.loading': 'Enregistrement...',
    'materials.map.title': "Localisation de l'entrepôt",
    'materials.map.description': "Définissez la position GPS de l'entrepôt et tracez sa forme et zone de stockage",
    'materials.toast.created': 'Matériau créé',
    'materials.toast.created_description': 'Le matériau "{name}" a été créé avec succès avec sa localisation.',
    'materials.toast.error': 'Erreur',
    'materials.toast.error_description': "Impossible de créer le matériau. Veuillez réessayer plus tard.",
    'materials.error.name_required': 'Le nom du matériau est requis',
    'materials.form.basic_info': 'Informations de base',
    'materials.form.workspace_location': 'Espace de travail et localisation',
    'materials.form.quantities_pricing': 'Quantités et prix',
    'materials.form.timeline': 'Chronologie',
    'materials.form.supplier_info': 'Informations fournisseur',
    'materials.name_placeholder': 'Ex: Ciment Portland',
    'materials.description_placeholder': 'Décrivez les caractéristiques du matériau...',
    'materials.workspace': 'Espace de travail',
    'materials.workspace_placeholder': 'Sélectionner un espace de travail',
    'materials.address_placeholder': 'Numéro, nom rue, code postal, ville, pays',
    'materials.available_quantity': 'Quantité disponible',
    'materials.min_quantity': 'Quantité minimale',
    'materials.timeline.start': 'Date de début',
    'materials.timeline.end': 'Date de fin',
    'materials.timeline.estimated_duration': 'Durée estimée (jours)',
    'materials.loading': 'Chargement des matériaux...',
    'materials.error_loading': 'Erreur lors du chargement des matériaux',
    'materials.retry': 'Réessayer',
    'materials.add': 'Ajouter un matériau',
    'materials.search_placeholder': 'Rechercher un matériau...',
    'materials.all_categories': 'Toutes les catégories',
    'materials.sort_by': 'Trier par',
    'materials.sort.name': 'Nom',
    'materials.sort.price': 'Prix',
    'materials.sort.quantity': 'Quantité',
    'materials.grid': 'Grille',
    'materials.map': 'Carte',
    'materials.unit_price': 'Prix unitaire',
    'materials.available': 'Disponible',
    'materials.not_defined': 'Non défini',
    'materials.warehouse_location': "Localisation de l'entrepôt",
    'materials.shape': 'Forme',
    'materials.edit': 'Modifier',
    'materials.delete': 'Supprimer',
    'materials.deleting': 'Suppression...',
    'materials.none_found': 'Aucun matériau trouvé',
    'materials.no_match': 'Aucun matériau ne correspond à vos critères de recherche.',
    'materials.add_first': 'Commencez par ajouter votre premier matériau.',
    'materials.no_geolocated': 'Aucun matériau géolocalisé',
    'materials.geolocated_hint': 'Les matériaux avec des coordonnées géographiques s\'afficheront ici.',
    'materials.map.empty_title': "Aucun projet géolocalisé",
    'materials.map.empty_desc': "Aucun projet avec des coordonnées géographiques n'a été trouvé.",
    'materials.map.warehouse': "Entrepôt",
    'materials.map.zone': "Zone",
    'materials.map.center': "Centre",
    'materials.map.shape': "Forme",
    'materials.map.instructions': "Cliquez pour ajouter des points à la zone. Cliquez sur \"Terminer\" quand vous avez fini.",
    'materials.map.finish': "Terminer",
    'materials.map.clear': "Effacer",
    'materials.map.latitude': "Latitude",
    'materials.map.longitude': "Longitude",
    'materials.map.apply': "Appliquer",
    'materials.map.drawing': "Tracé en cours...",
    'materials.map.draw.zone': "Tracer Zone",
    'materials.map.draw.warehouse': "Tracer Entrepôt",
    'materials.map.shape.type': "Type de forme:",
    'materials.map.shape.polygon': "Polygone",
    'materials.map.shape.rectangle': "Rectangle",
    'materials.map.shape.circle': "Cercle",
    'materials.map.status.center': "Centre",
    'materials.map.status.zone': "Zone tracée",
    'materials.map.status.warehouse': "Entrepôt tracé",
    'materials.map.status.points': "points",
    'map.mode.center': 'Centre',
    'map.mode.zone': 'Zone',
    'map.mode.warehouse': 'Entrepôt',
    'map.latitude': 'Latitude',
    'map.longitude': 'Longitude',
    'map.apply': 'Appliquer',
    'map.drawing': 'Tracé en cours...',
    'map.draw.zone': 'Tracer Zone',
    'map.draw.warehouse': 'Tracer Entrepôt',
    'map.finish': 'Terminer',
    'map.clear': 'Effacer',
    'map.shape.type': 'Type de forme:',
    'map.shape.polygon': 'Polygone',
    'map.shape.rectangle': 'Rectangle',
    'map.shape.circle': 'Cercle',
    'map.status.center': 'Centre',
    'map.status.zone': 'Zone tracée',
    'map.status.warehouse': 'Entrepôt tracé',
    'map.status.points': 'points',
    'map.instructions.polygon': 'Cliquez pour ajouter des points à la zone. Cliquez sur "Terminer" quand vous avez fini.',
    'map.instructions.rectangle.start': 'Cliquez pour définir le premier coin du rectangle',
    'map.instructions.rectangle.end': 'Cliquez pour définir le coin opposé du rectangle',
    'map.instructions.circle.start': 'Cliquez pour définir le centre du cercle',
    'map.instructions.circle.end': 'Cliquez pour définir le rayon du cercle',
    'map.instructions.warehouse.polygon': 'Cliquez pour ajouter des points au polygone. Cliquez sur "Terminer" quand vous avez fini.',
    'tender.input.title': 'Titre du document',
    'tender.input.description': 'Description',
    'tender.input.category': 'Catégorie',
    'tender.input.subcategory': 'Sous-catégorie',
    'tender.button.add': 'Ajouter',
    'tender.button.loading': 'Ajout en cours...',
    'tender.alert.upload_error': "Erreur lors de l'upload du fichier",
    'tender.alert.document_error': "Erreur lors de l'ajout du document",
    'tender.alert.tenderdoc_error': "Erreur lors de la création du TenderDocument",
    'tender.alert.success': "Document ajouté !",
    'tender_category.administrative': 'Administratif',
    'tender_category.technical': 'Technique',
    'tender_category.financial': 'Financier',
    'tender_subcategory.lettre_soumission': 'Lettre de soumission',
    'tender_subcategory.pouvoir_signature': 'Pouvoir de signature',
    'ts.empty': 'Aucune donnée à afficher',
    "task.subtitle": "Assignez et suivez les tâches de votre équipe",
    "task.title": "Tâches",
    "task.unassigned": "Non assigné",
    "task.assignments_title": "Affectations de Tâches",
    "task.create_sample_data": "Créer des données d'exemple",
    "task.new": "Nouvelle Tâche",
    "task.edit": "Modifier la Tâche",
    "task.select_project": "Sélectionner un projet",
    "task.assigned_to": "Assigné à",
    "task.select_employee": "Sélectionner un employé",
    "task.due_date": "Date d'échéance",
    "task.priority": "Priorité",
    "task.priority_low": "Faible",
    "task.priority_medium": "Moyenne",
    "task.priority_high": "Élevée",
    "task.status": "Statut",
    "task.status_pending": "En attente",
    "task.status_in_progress": "En cours",
    "task.status_completed": "Terminé",
    "task.status_cancelled": "Annulé",
    "task.description": "Description",
    "task.notes": "Notes",
    "task.update": "Mettre à jour",
    "task.create": "Créer",
    "task.cancel": "Annuler",
    "task.due": "Échéance",
    "task.created": "Créé",
    "task.none_found": "Aucune tâche trouvée",
    "task.total": "Total",
    "dev_mode.active": "Mode développement actif",
    "users.title": "Gestion des Utilisateurs",
    "users.new": "Nouvel Utilisateur",
    "users.search_placeholder": "Rechercher un utilisateur...",
    "users.table.name": "Utilisateur",
    "users.table.phone": "Téléphone",
    "users.table.national_id": "ID National",
    "users.table.role": "Rôle principal",
    "users.table.status": "Statut",
    "users.table.actions": "Actions",
    "users.no_results": "Aucun utilisateur ne correspond à la recherche",
    "users.none_found": "Aucun utilisateur trouvé",
    "users.no_name": "Utilisateur sans nom",
    "users.active": "Actif",
    "users.inactive": "Désactivé",
    "users.total": "Total: {count} utilisateur(s)",
    "users.details_title": "Détails de l'utilisateur",
    "users.phone": "Téléphone",
    "users.national_id": "ID National",
    "users.created_at": "Date d'inscription",
    "users.manage_roles": "Gérer les rôles",
    'users.created_successfully': "Employé créé avec succès",
    'users.deleted_successfully': "Employé supprimé avec succès",
    'users.created': "Utilisateur créé",
    'users.created_success': "Le nouvel utilisateur a été créé avec succès.",
    'users.updated': "Utilisateur mis à jour",
    'users.updated_success': "Les informations de l'utilisateur ont été mises à jour.",
    'error.title': "Erreur",
    'error.missing_fields': "Veuillez remplir tous les champs obligatoires.",
    'error.user_id_required': "ID utilisateur requis.",
    'error.generic': "Une erreur est survenue.",
    'loading': "Chargement...",
    'contact.title': 'Contactez-nous',
    'contact.form.title': 'Envoyez-nous un message',
    'contact.form.name': 'Nom',
    'contact.form.name_placeholder': 'Votre nom',
    'contact.form.email': 'Email',
    'contact.form.email_placeholder': 'votre.email@exemple.com',
    'contact.form.subject': 'Sujet',
    'contact.form.subject_placeholder': 'Sujet de votre message',
    'contact.form.message': 'Message',
    'contact.form.message_placeholder': 'Votre message...',
    'contact.form.send': 'Envoyer le message',
    'contact.alert.sent': 'Votre message a été envoyé. Nous vous répondrons dans les meilleurs délais.',
    'contact.info.title': 'Nos coordonnées',
    'contact.info.address': 'Adresse',
    'contact.info.address_value': '123 Avenue de la Construction\nNouakchott, Mauritanie',
    'contact.info.phone': 'Téléphone',
    'contact.info.phone_value': '+222 45 25 25 25',
    'contact.info.email': 'Email',
    'contact.info.email_value': 'contact@materiaux-gestion.mr',
    'contact.info.hours': "Heures d'ouverture",
    'contact.info.hours_value': 'Lundi - Vendredi: 8h00 - 17h00\nSamedi: 9h00 - 13h00\nDimanche: Fermé',
    'contact.info.social': 'Suivez-nous',
    'dashboard.title': 'Tableau de bord',
    'dashboard.active_projects': 'Projets en cours',
    'dashboard.status_overview': 'Statut général',
    'dashboard.active_projects_label': 'projets actifs',
    'dashboard.total_budget': 'Budget total',
    'dashboard.financial_resources': 'Ressources financières',
    'dashboard.team': 'Équipe',
    'dashboard.project_staff': 'Personnel de projet',
    'dashboard.members': 'membres',
    'dashboard.materials': 'Matériaux',
    'dashboard.available_resources': 'Ressources disponibles',
    'dashboard.types': 'types',
    'dashboard.project_progress': 'Progression des projets',
    'dashboard.no_data': 'Aucune donnée disponible',
    'dashboard.recent_projects': 'Projets récents',
    'dashboard.view_all': 'Voir tout',
    'dashboard.no_projects': 'Aucun projet disponible',
    'dashboard.distribution_by_region': 'Distribution par région',
    'dashboard.project_distribution': 'Distribution des projets',
    'dashboard.no_geolocated_projects': 'Aucun projet géolocalisé disponible',
    'dashboard.dev_mode': 'Mode développement actif',
    'dashboard.loading': 'Chargement du tableau de bord...',
    'index.loading': 'Chargement...',
    'index.features.title': 'Fonctionnalités Principales',
    'index.features.description': 'Découvrez toutes les fonctionnalités de notre plateforme de gestion de construction',
    'index.features.discover': 'Découvrir',
    'index.features.login_to_access': 'Se connecter pour accéder',
    'index.feature.projects.title': 'Gestion de Projets',
    'index.feature.projects.description': 'Suivez et gérez tous vos projets de construction en temps réel',
    'index.feature.materials.title': 'Gestion de Matériaux',
    'index.feature.materials.description': 'Inventaire et suivi des matériaux de construction',
    'index.feature.documents.title': 'Documentation',
    'index.feature.documents.description': 'Centralisez tous vos documents et rapports',
    'index.feature.teams.title': 'Équipes',
    'index.feature.teams.description': 'Gérez vos équipes et assignez les tâches',
    'index.feature.dashboard.title': 'Tableau de Bord',
    'index.feature.dashboard.description': 'Visualisez les performances et statistiques',
    'index.cta.title': 'Prêt à commencer ?',
    'index.cta.authenticated': 'Accédez à votre tableau de bord pour gérer vos projets',
    'index.cta.unauthenticated': 'Rejoignez-nous et transformez votre gestion de construction',
    'index.cta.dashboard': 'Tableau de Bord',
    'index.cta.my_projects': 'Mes Projets',
    'index.cta.start_free': 'Commencer Gratuitement',
    'index.cta.login': 'Se Connecter',
    // Documents Section
    'documents.title': 'Gestion des Documents',
    'documents.subtitle': 'Gérez tous vos documents de projet, contrats, rapports et informations',
    'documents.tabs.all': 'Tous',
    'documents.tabs.documents': 'Documents',
    'documents.tabs.tender': "Appels d'offres",
    'documents.tabs.suppliers': 'Fournisseurs',
    'documents.tabs.tasks': 'Tâches',
    'documents.tabs.employees': 'Employés',
    'documents.tabs.upload': 'Télécharger',
    'documents.tabs.viewer': 'Visionneuse',
    'documents.type.inspection_report': "Rapports d'inspection",
    'documents.type.location_photo': 'Photos de localisation',
    'documents.type.project_report': 'Rapports de projet',
    'documents.type.contract': 'Contrats',
    'documents.type.supplier_info': 'Informations fournisseurs',
    'documents.type.task_assignment': 'Affectations de tâches',
    'documents.type.employee_record': 'Dossiers employés',
    'documents.type.tender_documents': "Documents d'appel d'offres",
    'documents.card.click_to_view': 'Cliquez pour voir les documents de ce type',
    'documents.tender.title': "Documents d'Appel d'Offres",
    'documents.tender.select_project': 'Sélectionnez un projet pour voir ses documents d\'appel d\'offres',
    'documents.tender.select_project_placeholder': 'Sélectionner un projet...',
    'documents.tender.add_title': "Ajouter un document d'appel d'offres",
    'documents.tender.add_description': 'Remplissez le formulaire pour ajouter un document lié à ce projet.',
    'inspection.create.title': 'Créer une inspection',
    'inspection.create.description': "Création d'une inspection pour le projet: {projectId}",
    'inspection.create.in_development': 'En développement',
    'inspection.edit.title': "Modifier l'inspection",
    'inspection.edit.description': "Modification de l'inspection avec l'ID: {id}",
    'inspection.edit.in_development': "En développement",
    'inspection.dialog.validation_error': "Erreur de validation",
    'inspection.dialog.validation_inspector': "Veuillez saisir le nom de l'inspecteur.",
    'inspection.dialog.created': "Inspection créée",
    'inspection.dialog.created_description': "L'inspection a été enregistrée avec succès.",
    'inspection.dialog.error': "Erreur",
    'inspection.dialog.error_description': "Une erreur est survenue lors de la création de l'inspection.",
    'inspection.dialog.new_inspection': "Nouvelle Inspection",
    'inspection.dialog.title': "Créer une nouvelle inspection",
    'inspection.dialog.description': "Enregistrez les détails de l'inspection pour le projet \"{project}\".",
    'inspection.dialog.date': "Date d'inspection",
    'inspection.dialog.select_date': "Sélectionner une date",
    'inspection.dialog.inspector': "Inspecteur",
    'inspection.dialog.inspector_placeholder': "Nom de l'inspecteur",
    'inspection.dialog.status': "Statut",
    'inspection.dialog.select_status': "Sélectionner un statut",
    'inspection.dialog.status_pending': "En attente",
    'inspection.dialog.status_approved': "Approuvé",
    'inspection.dialog.status_requires_changes': "Modifications requises",
    'inspection.dialog.status_rejected': "Rejeté",
    'inspection.dialog.progress': "Progression du projet (%)",
    'inspection.dialog.comments': "Commentaires",
    'inspection.dialog.comments_placeholder': "Ajoutez des commentaires sur l'inspection...",
    'inspection.dialog.cancel': "Annuler",
    'inspection.dialog.create': "Créer l'inspection",
    'inspection.dialog.creating': "Création...",
    // Material Detail Section
    'material.detail.title': "Détail du matériau",
    'material.detail.description': "Détails du matériau avec l'ID: {id}",
    'material.detail.in_development': "En développement",
    'material.edit.title': "Modifier le matériau",
    'material.edit.description': "Modification du matériau avec l'ID: {id}",
    'material.edit.in_development': "En développement",
    // Not Found Section
    'notfound.message': "Oups ! Page non trouvée",
    'notfound.return_home': "Retour à l'accueil",
    // Privacy Policy Section
    "policy.title": "Politique de Confidentialité",
    "policy.last_update": "Dernière mise à jour : 16 mai 2025",
    "policy.section1.title": "1. Introduction",
    "policy.section1.text": "Nous nous engageons à protéger la vie privée et les données personnelles de nos utilisateurs. Cette politique de confidentialité explique comment nous recueillons, utilisons, divulguons et protégeons vos informations lorsque vous utilisez notre plateforme de gestion de matériaux et de projets.",
    "policy.section2.title": "2. Informations que nous recueillons",
    "policy.section2.text": "Nous recueillons les types d'informations suivants :",
    "policy.section2.item1": "Informations personnelles : nom, adresse e-mail, numéro de téléphone, identifiant national.",
    "policy.section2.item2": "Informations de compte : identifiants de connexion, préférences et paramètres.",
    "policy.section2.item3": "Données de projet : détails des projets, matériaux, inspections et paiements.",
    "policy.section2.item4": "Informations d'utilisation : comment vous interagissez avec notre plateforme, les fonctionnalités utilisées et le temps passé.",
    "policy.section3.title": "3. Comment nous utilisons vos informations",
    "policy.section3.text": "Nous utilisons vos informations pour :",
    "policy.section3.item1": "Fournir et maintenir nos services.",
    "policy.section3.item2": "Améliorer, personnaliser et développer notre plateforme.",
    "policy.section3.item3": "Communiquer avec vous, y compris vous envoyer des mises à jour sur nos services.",
    "policy.section3.item4": "Assurer la sécurité de notre plateforme.",
    "policy.section3.item5": "Se conformer aux obligations légales.",
    "policy.section4.title": "4. Partage des informations",
    "policy.section4.text": "Nous ne partageons vos informations personnelles qu'avec :",
    "policy.section4.item1": "Les membres de votre équipe ou organisation ayant accès au même projet.",
    "policy.section4.item2": "Nos fournisseurs de services tiers qui nous aident à exploiter notre plateforme.",
    "policy.section4.item3": "Les autorités légales lorsque nous sommes légalement tenus de le faire.",
    "policy.section5.title": "5. Sécurité des données",
    "policy.section5.text": "Nous mettons en œuvre des mesures de sécurité appropriées pour protéger vos informations personnelles contre l'accès non autorisé, l'altération, la divulgation ou la destruction.",
    "policy.section6.title": "6. Vos droits",
    "policy.section6.text": "Vous avez le droit de :",
    "policy.section6.item1": "Accéder à vos données personnelles.",
    "policy.section6.item2": "Rectifier vos données personnelles si elles sont inexactes.",
    "policy.section6.item3": "Demander l'effacement de vos données personnelles.",
    "policy.section6.item4": "Restreindre ou vous opposer au traitement de vos données.",
    "policy.section6.item5": "Demander la portabilité de vos données.",
    "policy.section7.title": "7. Modifications de cette politique",
    "policy.section7.text": "Nous pouvons mettre à jour cette politique de confidentialité périodiquement. Nous vous informerons de tout changement en publiant la nouvelle politique de confidentialité sur cette page.",
    "policy.section8.title": "8. Contact",
    "policy.section8.text": "Si vous avez des questions concernant cette politique de confidentialité, veuillez nous contacter à privacy@materiaux-gestion.mr.",
    'terms.title': "Conditions Générales d'Utilisation",
    'terms.last_update': "Dernière mise à jour",
    'terms.section1.title': "1. Acceptation des conditions",
    'terms.section1.text': "En accédant et en utilisant cette plateforme de gestion de matériaux et de projets, vous acceptez d'être lié par ces Conditions Générales d'Utilisation. Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser cette plateforme.",
    'terms.section2.title': "2. Description du service",
    'terms.section2.text': "Notre plateforme offre des outils de gestion de projets et de matériaux pour les secteurs de la construction et des travaux publics. Les fonctionnalités comprennent le suivi des projets, la gestion des matériaux, les inspections, et le suivi financier.",
    'terms.section3.title': "3. Comptes utilisateurs",
    'terms.section3.text': "Pour accéder à certaines fonctionnalités de la plateforme, vous devez créer un compte. Vous êtes responsable de maintenir la confidentialité de vos informations de compte et de toutes les activités qui se produisent sous votre compte.",
    'terms.section4.title': "4. Utilisation appropriée",
    'terms.section4.text': "Vous acceptez d'utiliser la plateforme uniquement à des fins légales et d'une manière qui ne viole pas les droits d'autrui ou ne restreint pas leur utilisation de la plateforme.",
    'terms.section5.title': "5. Propriété intellectuelle",
    'terms.section5.text': "Tout le contenu présent sur la plateforme, y compris les textes, graphiques, logos, icônes et images, est la propriété de notre entreprise et est protégé par les lois sur la propriété intellectuelle.",
    'terms.section6.title': "6. Limitation de responsabilité",
    'terms.section6.text': "Notre entreprise ne sera pas responsable des dommages directs, indirects, accessoires, consécutifs ou punitifs résultant de votre accès ou utilisation de la plateforme.",
    'terms.section7.title': "7. Modifications des conditions",
    'terms.section7.text': "Nous nous réservons le droit de modifier ces conditions à tout moment. Les modifications entreront en vigueur dès leur publication sur la plateforme. Votre utilisation continue de la plateforme après la publication des modifications constitue votre acceptation de ces modifications.",
    'terms.section8.title': "8. Contact",
    'terms.section8.text': "Si vous avez des questions concernant ces conditions, veuillez nous contacter à l'adresse électronique support@materiaux-gestion.mr ou par téléphone au +222 45 25 25 25.",
    'footer.about': "À propos",
    'footer.about_desc': "Plateforme de gestion des matériaux et des projets pour le secteur de la construction et des travaux publics en Mauritanie. Optimisez vos ressources, suivez vos projets et collaborez efficacement.",
    'footer.rights': "Tous droits réservés.",
    'footer.by_hadratech': "Développé par Hadratech",
    'footer.quick_links': "Liens rapides",
    'footer.legal': "Légal",
    'project_create.title': 'Créer un projet',
    'project_create.tabs.form': 'Formulaire',
    'project_create.tabs.materials': 'Matériaux',
    'project_create.tabs.map': 'Carte',
    'project_create.name_label': 'Nom du projet',
    'project_create.name_placeholder': 'Entrez le nom du projet',
    'project_create.form.description': 'Description',
    'project_create.form.description_placeholder': 'Décrivez le projet...',
    'project_create.start_date': 'Date de début',
    'project_create.end_date': 'Date de fin (optionnelle)',
    'project_create.location': 'Localisation',
    'project_create.submit': 'Créer le projet',
    'project_create.cancel': 'Annuler',
    'project_create.form.budget': 'Budget du projet',
    'project_create.form.progress': 'Progression du projet',
    'project_create.form.team_label': 'Équipe du projet',
    'project_create.form.team_placeholder': 'Sélectionnez les membres de léquipe',
    'project_create.form.team_size': 'Taille de léquipe',
    'project_create.back_to_projects': 'Retour à la liste des projets',
    'project_create.form.team.help': 'Ajoutez les membres qui participeront à ce projet',
    'project_create.form.budget.help': 'Indiquez le budget total alloué à ce projet',
    'project_create.form.progress.help': 'Indiquez lavancement actuel du projet en pourcentage',
    'project_create.form.team_size.help': 'Nombre total de personnes dans léquipe du projet',
    'project_create.form.title': 'Informations du projet',
   'project_create.toast.geolocation_not_supported': "Géolocalisation non supportée",
    'project_create.toast.geolocation_not_supported_desc': "Votre navigateur ne supporte pas la géolocalisation.",
    'project_create.toast.geolocation_error': "Erreur de géolocalisation",
    'project_create.toast.geolocation_unavailable': "Impossible d'obtenir votre position actuelle.",
    'project_create.toast.position_selected': "Position sélectionnée",
    'project_create.toast.materials_error': "Erreur lors de l'ajout des matériaux",
    'project_create.toast.materials_error_desc': "Impossible d'ajouter les matériaux au projet.",
    'project_create.toast.created': "Projet créé",
    'project_create.toast.created_desc': "Le projet \"{title}\" a été créé avec succès.",
    'project_create.toast.error': "Erreur lors de la création du projet",
    'project_create.toast.error_desc': "Impossible de créer le projet. Veuillez réessayer.",
    'project_create.form.budget_desc': 'Indiquez le budget total prévu pour ce projet',
    'project_create.form.start_date': 'Date de début du projet',
    'project_create.form.status': 'Statut du projet',
    'project_create.form.location': 'Lieu du projet',
    'project_create.form.latitude': 'Latitude',
    'project_create.form.longitude': 'Longitude',
    'project_create.map.click_hint': 'Cliquez sur la carte pour sélectionner la position du projet',
    'project_create.status.pending': 'En attente',
    'project_create.status.ongoing': 'En cours',
    'project_create.status.completed': 'Terminé',
    'project_create.status.suspended': 'Suspendu',
    'project_create.status.cancelled': 'Annulé',
    'materials.required': 'Veuillez sélectionner au moins un matériau',
    'project_create.materials.back_to_form': 'Retour au formulaire',
    'project_create.form.create': 'Créer le projet',
    'project_create.from_materials': 'Depuis les matériaux',
    'project_create.form.add_materials': 'Ajouter des matériaux',
    'project.title': 'Projet',
    'project.name': 'Nom du projet',
    'project.status': 'Statut',
    'project.start_date': 'Date de début',
    'project.end_date': 'Date de fin',
    'project.location': 'Localisation',
    'project.description': 'Description',
    'project.manager': 'Chef de projet',
    'project.team': 'Équipe',
    'project.budget': 'Budget',
    'project.progress': 'Progression',
    'project.actions': 'Actions',
    'project.edit': 'Modifier le projet',
    'project.delete': 'Supprimer le projet',
    'project.save': 'Enregistrer',
    'project.cancel': 'Annuler',
    'project.confirm_delete': 'Êtes-vous sûr de vouloir supprimer ce projet ?',
    'project.none_found': 'Aucun projet trouvé',
    'project.add': 'Ajouter un projet',
    'payment.title': 'Paiements',
    'payment.new': 'Nouveau paiement',
    'payment.amount': 'Montant',
    'payment.date': 'Date de paiement',
    'payment.method': 'Méthode de paiement',
    'payment.status': 'Statut',
    'payment.description': 'Description',
    'payment.add': 'Ajouter un paiement',
    'payment.edit': 'Modifier le paiement',
    'payment.delete': 'Supprimer le paiement',
    'payment.confirm_delete': 'Êtes-vous sûr de vouloir supprimer ce paiement ?',
    'payment.save': 'Enregistrer',
    'payment.none_found': 'Aucun paiement trouvé',
    'payment.success': 'Paiement enregistré avec succès',
    'payment.error': 'Erreur lors de l\'enregistrement du paiement',
    'toast.saved_title': 'Enregistré',
    'toast.saved_description': 'Les informations ont été enregistrées avec succès.',
    'elements.measured': 'Éléments mesurés',
    'total.value': 'Valeur totale',
    'total.quantity': 'Quantité totale'
  },
  ar: {
    'projects.title': ' مشاريع',
    'projects.header.title':' مشاريع',
    'projects.header.add':' مشاريع add',
    'projects.header.subtitle':'مشاريع',
    'projects.tab.map': ' خرائط',
    'projects.tab.list': ' مشاريع',
    'language.french': "فرنسية",
    'language.english': " انكليزية",
    'language.arabic': "عربية",
    "users.title": "إدارة المستخدمين",
    "users.new": "مستخدم جديد",
    "users.search_placeholder": "ابحث عن مستخدم...",
    "users.table.name": "المستخدم",
    "users.table.phone": "الهاتف",
    "users.table.national_id": "الرقم الوطني",
    "users.table.role": "الدور الرئيسي",
    "users.table.status": "الحالة",
    "users.table.actions": "إجراءات",
    "users.no_results": "لا يوجد مستخدم يطابق البحث",
    "users.none_found": "لم يتم العثور على مستخدمين",
    "users.no_name": "مستخدم بدون اسم",
    "users.phone": "الهاتف",
    "users.national_id": "الرقم الوطني",
    "users.created_at": "تاريخ التسجيل",
    "users.total": "الإجمالي: {count} مستخدم(ين)",
    "users.details_title": "تفاصيل المستخدم",
    "users.manage_roles": "إدارة الأدوار",
    'users.created_successfully': "تم إنشاء الموظف بنجاح",
    'users.deleted_successfully': "تم حذف الموظف بنجاح",
    'users.created': "تم إنشاء المستخدم",
    'users.created_success': "تم إنشاء المستخدم الجديد بنجاح.",
    'users.updated': "تم تحديث المستخدم",
    'users.updated_success': "تم تحديث معلومات المستخدم.",
    'error.title': "خطأ",
    'error.missing_fields': "يرجى ملء جميع الحقول المطلوبة.",
    'error.user_id_required': "معرف المستخدم مطلوب.",
    'error.generic': "حدث خطأ ما.",
    'roles.assigned': "تم تعيين الدور",
    'roles.assigned_success': "تم تعيين الدور {role} بنجاح.",
    'roles.assign_error': "تعذر تعيين الدور.",
    'roles.removed': "تم إزالة الدور",
    'roles.removed_success': "تمت إزالة الدور {role} بنجاح.",
    'roles.remove_error': "تعذر إزالة الدور.",
    'loading': "جار التحميل...",
    'contact.title': 'اتصل بنا',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.name': 'الاسم',
    'contact.form.name_placeholder': 'اسمك',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.email_placeholder': 'your@email.com',
    'contact.form.subject': 'الموضوع',
    'contact.form.subject_placeholder': 'موضوع رسالتك',
    'contact.form.message': 'الرسالة',
    'contact.form.message_placeholder': 'اكتب رسالتك هنا...',
    'contact.form.send': 'إرسال الرسالة',
    'contact.alert.sent': 'تم إرسال رسالتك. سنرد عليك في أقرب وقت ممكن.',
    'contact.info.title': 'معلومات التواصل',
    'contact.info.address': 'العنوان',
    'contact.info.address_value': '123 شارع البناء\nنواكشوط، موريتانيا',
    'contact.info.phone': 'الهاتف',
    'contact.info.phone_value': '+222 45 25 25 25',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.email_value': 'contact@materiaux-gestion.mr',
    'contact.info.hours': "ساعات العمل",
    'contact.info.hours_value': 'الاثنين - الجمعة: 8:00 - 17:00\nالسبت: 9:00 - 13:00\nالأحد: مغلق',
    'contact.info.social': 'تابعنا',
    'project_create.tabs.form': 'النموذج',
    'project_create.tabs.materials': 'المواد',
    'project_create.tabs.map': 'الخريطة',
    'materials.required': 'يرجى اختيار مادة واحدة على الأقل',
    'project_create.materials.back_to_form': 'العودة إلى النموذج',
    'project_create.form.create': 'إنشاء المشروع',
    'project_create.from_materials': 'من المواد',
    'project_create.form.add_materials': 'إضافة مواد',
    'project.title': 'المشروع',
    'project.name': 'اسم المشروع',
    'project.status': 'الحالة',
    'project.start_date': 'تاريخ البدء',
    'project.end_date': 'تاريخ الانتهاء',
    'project.location': 'الموقع',
    'project.description': 'الوصف',
    'project.manager': 'مدير المشروع',
    'project.team': 'الفريق',
    'project.budget': 'الميزانية',
    'project.progress': 'التقدم',
    'project.actions': 'الإجراءات',
    'project.edit': 'تعديل المشروع',
    'project.delete': 'حذف المشروع',
    'project.save': 'حفظ',
    'project.cancel': 'إلغاء',
    'project.confirm_delete': 'هل أنت متأكد أنك تريد حذف هذا المشروع؟',
    'project.none_found': 'لم يتم العثور على مشاريع',
    'project.add': 'إضافة مشروع',
    'payment.title': 'المدفوعات',
    'payment.new': 'دفعة جديدة',
    'payment.amount': 'المبلغ',
    'payment.date': 'تاريخ الدفع',
    'payment.method': 'طريقة الدفع',
    'payment.status': 'الحالة',
    'payment.description': 'الوصف',
    'payment.add': 'إضافة دفعة',
    'payment.edit': 'تعديل الدفعة',
    'payment.delete': 'حذف الدفعة',
    'payment.confirm_delete': 'هل أنت متأكد أنك تريد حذف هذه الدفعة؟',
    'payment.save': 'حفظ',
    'payment.none_found': 'لا توجد مدفوعات',
    'payment.success': 'تم حفظ الدفعة بنجاح',
    'payment.error': 'حدث خطأ أثناء حفظ الدفعة',
    "policy.title": "سياسة الخصوصية",
    "policy.last_update": "آخر تحديث: 16 مايو 2025",
    "policy.section1.title": "1. المقدمة",
    "policy.section1.text": "نحن ملتزمون بحماية خصوصية وبيانات مستخدمينا. توضح سياسة الخصوصية هذه كيفية جمعنا واستخدامنا والإفصاح عن معلوماتك وحمايتها عند استخدامك لمنصتنا لإدارة المواد والمشاريع.",
    "policy.section2.title": "2. المعلومات التي نجمعها",
    "policy.section2.text": "نجمع الأنواع التالية من المعلومات:",
    "policy.section2.item1": "معلومات شخصية: الاسم، البريد الإلكتروني، رقم الهاتف، الرقم الوطني.",
    "policy.section2.item2": "معلومات الحساب: بيانات تسجيل الدخول، التفضيلات والإعدادات.",
    "policy.section2.item3": "بيانات المشروع: تفاصيل المشاريع، المواد، الفحوصات والمدفوعات.",
    "policy.section2.item4": "معلومات الاستخدام: كيف تتفاعل مع منصتنا، الميزات المستخدمة والوقت المستغرق.",
    "policy.section3.title": "3. كيف نستخدم معلوماتك",
    "policy.section3.text": "نستخدم معلوماتك من أجل:",
    "policy.section3.item1": "تقديم خدماتنا وصيانتها.",
    "policy.section3.item2": "تحسين وتخصيص وتطوير منصتنا.",
    "policy.section3.item3": "التواصل معك، بما في ذلك إرسال التحديثات حول خدماتنا.",
    "policy.section3.item4": "ضمان أمان منصتنا.",
    "policy.section3.item5": "الامتثال للالتزامات القانونية.",
    "policy.section4.title": "4. مشاركة المعلومات",
    "policy.section4.text": "نحن لا نشارك معلوماتك الشخصية إلا مع:",
    "policy.section4.item1": "أعضاء فريقك أو منظمتك الذين لديهم حق الوصول لنفس المشروع.",
    "policy.section4.item2": "مزودي الخدمة الخارجيين الذين يساعدوننا في تشغيل منصتنا.",
    "policy.section4.item3": "السلطات القانونية عندما نكون ملزمين قانونياً بذلك.",
    "policy.section5.title": "5. أمان البيانات",
    "policy.section5.text": "نطبق تدابير أمان مناسبة لحماية معلوماتك الشخصية من الوصول غير المصرح به أو التغيير أو الإفصاح أو التدمير.",
    "policy.section6.title": "6. حقوقك",
    "policy.section6.text": "لديك الحق في:",
    "policy.section6.item1": "الوصول إلى بياناتك الشخصية.",
    "policy.section6.item2": "تصحيح بياناتك الشخصية إذا كانت غير دقيقة.",
    "policy.section6.item3": "طلب حذف بياناتك الشخصية.",
    "policy.section6.item4": "تقييد أو الاعتراض على معالجة بياناتك.",
    "policy.section6.item5": "طلب نقل بياناتك.",
    "policy.section7.title": "7. تعديلات على هذه السياسة",
    "policy.section7.text": "قد نقوم بتحديث سياسة الخصوصية هذه بشكل دوري. سنخطرك بأي تغييرات من خلال نشر السياسة الجديدة على هذه الصفحة.",
    "policy.section8.title": "8. التواصل",
    "policy.section8.text": "إذا كان لديك أي أسئلة بخصوص سياسة الخصوصية هذه، يرجى التواصل معنا على privacy@materiaux-gestion.mr.",
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.projects': 'المشاريع',
    'nav.materials': 'المواد',
    'nav.users': 'المستخدمون',
    'nav.login': 'تسجيل الدخول',
    'nav.profile': 'الملف الشخصي',

    // Documents
    'documents.title': 'إدارة المستندات',
    'documents.subtitle': 'إدارة جميع مستندات المشروع والعقود والتقارير والمعلومات',
    'documents.tabs.all': 'الكل',
    'documents.tabs.documents': 'المستندات',
    'documents.tabs.tender': "المناقصات",
    'documents.tabs.suppliers': 'الموردون',
    'documents.tabs.tasks': 'المهام',
    'documents.tabs.employees': 'الموظفون',
    'documents.tabs.upload': 'رفع',
    'documents.tabs.viewer': 'عارض',
    'documents.type.inspection_report': "تقارير الفحص",
    'documents.type.location_photo': 'صور الموقع',
    'documents.type.project_report': 'تقارير المشروع',
    'documents.type.contract': 'العقود',
    'documents.type.supplier_info': 'معلومات الموردين',
    'documents.type.task_assignment': 'تعيينات المهام',
    'documents.type.employee_record': 'سجلات الموظفين',
    'documents.type.tender_documents': "مستندات المناقصة",
    'documents.card.click_to_view': 'انقر لعرض مستندات هذا النوع',
    'documents.tender.title': "مستندات المناقصة",
    'documents.tender.select_project': 'اختر مشروعاً لعرض مستنداته',
    'documents.tender.select_project_placeholder': 'اختر مشروعاً...',
    'documents.tender.add_title': "إضافة مستند مناقصة",
    'documents.tender.add_description': 'املأ النموذج لإضافة مستند متعلق بهذا المشروع.',
    "task.subtitle": "قم بتعيين وتتبع مهام فريقك",
    "task.title": "المهام",
    "task.unassigned": "غير معين",
    "task.assignments_title": "تعيينات المهام",
    "task.create_sample_data": "إنشاء بيانات تجريبية",
    "task.new": "مهمة جديدة",
    "task.edit": "تعديل المهمة",
    "task.select_project": "اختر مشروعاً",
    "task.assigned_to": "مُعين إلى",
    "task.select_employee": "اختر موظفاً",
    "task.due_date": "تاريخ الاستحقاق",
    "task.priority": "الأولوية",
    "task.priority_low": "منخفضة",
    "task.priority_medium": "متوسطة",
    "task.priority_high": "مرتفعة",
    "task.status": "الحالة",
    "task.status_pending": "قيد الانتظار",
    "task.status_in_progress": "قيد التنفيذ",
    "task.status_completed": "مكتملة",
    "task.status_cancelled": "ملغاة",
    "task.description": "الوصف",
    "task.notes": "ملاحظات",
    "task.update": "تحديث",
    "task.create": "إنشاء",
    "task.cancel": "إلغاء",
    "task.due": "الاستحقاق",
    "task.created": "تم الإنشاء",
    "task.none_found": "لم يتم العثور على مهام",
    "task.total": "الإجمالي",
    'toast.saved_title': 'تم الحفظ',
    'toast.saved_description': 'تم حفظ المعلومات بنجاح.',
    'elements.measured': 'العناصر المقاسة',
    'total.value': 'القيمة الإجمالية',
    'total.quantity': 'الكمية الإجمالية',
    'inspection.dialog.title': "إنشاء فحص جديد",
    'inspection.dialog.new_inspection': "فحص جديد",
    'inspection.dialog.description': "سجل تفاصيل الفحص للمشروع \"{project}\".",
    'inspection.dialog.date': "تاريخ الفحص",
    'inspection.dialog.inspector': "المفتش",
    'inspection.dialog.progress': "تقدم المشروع (%)",
    'inspection.dialog.comments': "ملاحظات",
    'inspection.dialog.status_approved': "معتمد",
    'inspection.dialog.status_pending': "قيد الانتظار",
    'inspection.dialog.status_requires_changes': "يتطلب تعديلات",
    'inspection.dialog.status_rejected': "مرفوض",
    'projects.progress_done': 'منجز',
    'projects.overview.description': 'وصف المشروع',
    'project_create.title': 'إنشاء مشروع',
    'project_create.name_placeholder': 'أدخل اسم المشروع',
    'project_create.form.description': 'الوصف',
    'project_create.form.description_placeholder': 'صف المشروع...',
    'project_create.form.location': 'موقع المشروع',
    'project_create.form.location_placeholder': 'المدينة أو المنطقة أو العنوان',
    'project_create.form.status': 'حالة المشروع',
    'project_create.form.status_placeholder': 'اختر الحالة',
    'project_create.status.pending': 'قيد الانتظار',
    'project_create.status.ongoing': 'قيد التنفيذ',
    'project_create.status.completed': 'مكتمل',
    'project_create.status.suspended': 'معلق',
    'project_create.status.cancelled': 'ملغى',
    'project_create.form.progress': 'تقدم المشروع',
    'project_create.form.progress_placeholder': '0-100',
    'project_create.form.progress_desc': 'حدد نسبة تقدم المشروع.',
    'project_create.form.progress_current': 'التقدم الحالي',
    'project_create.form.budget': 'ميزانية المشروع',
    'project_create.form.budget_placeholder': 'المبلغ بالأوقية',
    'project_create.form.budget_desc': 'حدد الميزانية الإجمالية المتوقعة لهذا المشروع',
    'project_create.form.team_size': "حجم الفريق",
    'project_create.form.team_size_placeholder': "عدد الأعضاء",
    'project_create.form.start_date': 'تاريخ بدء المشروع',
    'project_create.form.latitude': 'خط العرض',
    'project_create.form.latitude_placeholder': 'مثال: 18.079052',
    'project_create.form.longitude': 'خط الطول',
    'project_create.form.longitude_placeholder': 'مثال: -15.965634',
    'project_create.form.select_on_map': 'اختر من الخريطة',
    'project_create.form.creating': 'جاري الإنشاء...',
    'project_create.map.click_hint': 'انقر على الخريطة لتحديد موقع المشروع',
    'project_create.map.my_position': 'موقعي',
    'project_create.map.selected_position': 'الموقع المحدد',
    'project_create.map.latitude': 'خط العرض',
    'project_create.map.longitude': 'خط الطول',
    'project_create.map.back_to_form': 'العودة إلى النموذج',
    'project_create.back_to_projects': 'العودة إلى قائمة المشاريع',
    'project_create.toast.position_selected': 'تم تحديد الموقع',
    'project_create.toast.geolocation_error': 'خطأ في تحديد الموقع الجغرافي',
    'project_create.toast.geolocation_unavailable': "تعذر الحصول على موقعك الحالي.",
    'project_create.toast.geolocation_not_supported': "المتصفح لا يدعم تحديد الموقع الجغرافي",
    'project_create.toast.geolocation_not_supported_desc': "متصفحك لا يدعم تحديد الموقع الجغرافي.",
    'project_create.toast.created': "تم إنشاء المشروع",
    'project_create.toast.created_desc': "تم إنشاء المشروع \"{title}\" بنجاح.",
    'project_create.toast.error': "خطأ أثناء إنشاء المشروع",
    'project_create.toast.error_desc': "تعذر إنشاء المشروع. يرجى المحاولة مرة أخرى.",
    'project_create.toast.materials_error': "خطأ أثناء إضافة المواد",
    'project_create.toast.materials_error_desc': "تعذر إضافة المواد للمشروع.",
    'terms.title': "شروط الاستخدام",
    'terms.last_update': "آخر تحديث",
    'terms.section1.title': "1. قبول الشروط",
    'terms.section1.text': "بدخولك واستخدامك لهذه المنصة لإدارة المواد والمشاريع، فإنك توافق على الالتزام بهذه الشروط والأحكام. إذا كنت لا توافق على هذه الشروط، يرجى عدم استخدام المنصة.",
    'terms.section2.title': "2. وصف الخدمة",
    'terms.section2.text': "توفر منصتنا أدوات لإدارة المشاريع والمواد لقطاع البناء والأشغال العامة. تشمل الميزات تتبع المشاريع، إدارة المواد، الفحوصات، والمتابعة المالية.",
    'terms.section3.title': "3. حسابات المستخدمين",
    'terms.section3.text': "للوصول إلى بعض ميزات المنصة، يجب عليك إنشاء حساب. أنت مسؤول عن الحفاظ على سرية معلومات حسابك وجميع الأنشطة التي تتم من خلاله.",
    'terms.section4.title': "4. الاستخدام المناسب",
    'terms.section4.text': "توافق على استخدام المنصة فقط لأغراض قانونية وبطريقة لا تنتهك حقوق الآخرين أو تقيد استخدامهم للمنصة.",
    'terms.section5.title': "5. الملكية الفكرية",
    'terms.section5.text': "جميع المحتويات الموجودة على المنصة، بما في ذلك النصوص والرسومات والشعارات والرموز والصور، هي ملك لشركتنا ومحميّة بموجب قوانين الملكية الفكرية.",
    'terms.section6.title': "6. تحديد المسؤولية",
    'terms.section6.text': "لن تكون شركتنا مسؤولة عن أي أضرار مباشرة أو غير مباشرة أو عرضية أو تبعية أو عقابية ناتجة عن وصولك أو استخدامك للمنصة.",
    'terms.section7.title': "7. تعديلات الشروط",
    'terms.section7.text': "نحتفظ بالحق في تعديل هذه الشروط في أي وقت. تصبح التعديلات سارية فور نشرها على المنصة. استمرارك في استخدام المنصة بعد نشر التعديلات يعتبر قبولاً منك لهذه التعديلات.",
    'terms.section8.title': "8. التواصل",
    'terms.section8.text': "إذا كان لديك أي أسئلة بخصوص هذه الشروط، يرجى التواصل معنا عبر البريد الإلكتروني support@materiaux-gestion.mr أو الهاتف +222 45 25 25 25.",
    // --- auth.* ---
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'تسجيل حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.remember_me': 'تذكرني',
    'auth.forgot_password': 'هل نسيت كلمة المرور؟',
    'auth.full_name': 'الاسم الكامل',
    'auth.phone': 'الهاتف',
    'auth.national_id': 'الرقم الوطني',
    'auth.accept_terms': 'أوافق على شروط الاستخدام وسياسة الخصوصية',
    'auth.submit': 'إرسال',
    'auth.sign_in_with_google': 'الدخول عبر جوجل',
    'auth.sign_in_with_phone': 'عن طريق الهاتف',
    'auth.sign_in_with_national_id': 'عن طريق الرقم الوطني',
    'auth.or_continue_with': 'أو المتابعة بواسطة',
    'auth.or_register_with': 'أو التسجيل بواسطة',
    'auth.create_account': 'إنشاء حساب',
    'auth.welcome': 'مرحباً',
    'auth.connect_to_continue': 'سجّل الدخول للمتابعة',
    'auth.simulated_registration': 'تسجيل تجريبي',
    'auth.simulated_registration_description': 'هذا تسجيل تجريبي في وضع التطوير.',
    'auth.simulated_login': 'تسجيل دخول تجريبي',
    'auth.reset_password': 'هل نسيت كلمة المرور؟',
    'auth.send_code': 'استلام رمز',
    'auth.verify_code': 'تأكيد الرمز',
    'auth.use_other_phone': 'استخدم رقم هاتف آخر',
    'auth.use_email_login': 'العودة لتسجيل الدخول بالبريد',
    'auth.use_national_id_login': 'الدخول بالرقم الوطني',
    'auth.password_requirements': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
    'auth.terms': 'شروط الاستخدام',
    'auth.privacy': 'سياسة الخصوصية',
    'auth.error.invalid_credentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة. يرجى التحقق والمحاولة مرة أخرى.',
    'auth.button.loading': 'جار التحميل...',
    'auth.signup_disabled': 'التسجيل معطل',
    'auth.signup_disabled_description': 'التسجيل معطل حالياً.',
    'auth.weak_password': 'كلمة مرور ضعيفة',
    'auth.weak_password_description': 'كلمة المرور لا تحقق متطلبات الأمان.',
    'auth.authentication_error': 'خطأ في المصادقة',
    'auth.unexpected_error': 'حدث خطأ غير متوقع.',
    'auth.logout': 'تسجيل الخروج',
    'auth.menu': 'القائمة',

    // --- footer.* ---
    'footer.about': 'حول',
    'footer.about_desc': 'منصة إدارة المواد والمشاريع لقطاع البناء والأشغال العامة في موريتانيا. قم بتحسين مواردك، وتتبع مشاريعك وتعاون بكفاءة.',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.by_hadratech': 'تم التطوير بواسطة حضراتك',
    'footer.quick_links': 'روابط سريعة',
    'footer.legal': 'قانوني',

    // --- dashboard.* ---
    'dashboard.title': 'لوحة التحكم',
    'dashboard.active_projects': 'المشاريع النشطة',
    'dashboard.status_overview': 'نظرة عامة على الحالة',
    'dashboard.active_projects_label': 'مشاريع نشطة',
    'dashboard.total_budget': 'إجمالي الميزانية',
    'dashboard.financial_resources': 'الموارد المالية',
    'dashboard.team': 'الفريق',
    'dashboard.project_staff': 'فريق المشروع',
    'dashboard.members': 'أعضاء',
    'dashboard.materials': 'المواد',
    'dashboard.available_resources': 'الموارد المتاحة',
    'dashboard.types': 'أنواع',
    'dashboard.project_progress': 'تقدم المشاريع',
    'dashboard.no_data': 'لا توجد بيانات متاحة',
    'dashboard.recent_projects': 'المشاريع الأخيرة',
    'dashboard.view_all': 'عرض الكل',
    'dashboard.no_projects': 'لا توجد مشاريع متاحة',
    'dashboard.distribution_by_region': 'التوزيع حسب المنطقة',
    'dashboard.project_distribution': 'توزيع المشاريع',
    'dashboard.no_geolocated_projects': 'لا توجد مشاريع جغرافية متاحة',
    'dashboard.dev_mode': 'وضع التطوير مفعل',
    'dashboard.loading': 'جاري تحميل لوحة التحكم...',

    // --- materials.* ---
    'materials.title': 'المواد',
    'materials.new': 'مادة جديدة',
    'materials.name': 'اسم المادة',
    'materials.category': 'الفئة',
    'materials.price': 'سعر الوحدة',
    'materials.quantity': 'الكمية',
    'materials.unit': 'الوحدة',
    'materials.description': 'الوصف',
    'materials.address': 'العنوان',
    'materials.button.save': 'حفظ المادة',
    'materials.button.loading': 'جار الحفظ...',
    'materials.map.title': 'موقع المستودع',
    'materials.map.description': 'حدد موقع GPS للمستودع وارسم شكله ومنطقة التخزين',
    'materials.toast.created': 'تم إنشاء المادة',
    'materials.toast.created_description': 'تم إنشاء المادة "{name}" بنجاح مع موقعها.',
    'materials.toast.error': 'خطأ',
    'materials.toast.error_description': 'تعذر إنشاء المادة. يرجى المحاولة لاحقاً.',
    'materials.error.name_required': 'اسم المادة مطلوب',
    'materials.form.basic_info': 'معلومات أساسية',
    'materials.form.workspace_location': 'مكان العمل والموقع',
    'materials.form.quantities_pricing': 'الكميات والأسعار',
    'materials.form.timeline': 'الجدول الزمني',
    'materials.form.supplier_info': 'معلومات المورد',
    'materials.name_placeholder': 'مثال: أسمنت بورتلاند',
    'materials.description_placeholder': 'صف خصائص المادة...',
    'materials.workspace': 'مكان العمل',
    'materials.workspace_placeholder': 'اختر مكان العمل',
    'materials.address_placeholder': 'رقم، اسم الشارع، الرمز البريدي، المدينة، الدولة',
    'materials.available_quantity': 'الكمية المتاحة',
    'materials.min_quantity': 'الحد الأدنى للكمية',
    'materials.timeline.start': 'تاريخ البدء',
    'materials.timeline.end': 'تاريخ الانتهاء',
    'materials.timeline.estimated_duration': 'المدة المقدرة (أيام)',
    'materials.loading': 'جار تحميل المواد...',
    'materials.error_loading': 'حدث خطأ أثناء تحميل المواد',
    'materials.retry': 'إعادة المحاولة',
    'materials.add': 'إضافة مادة',
    'materials.search_placeholder': 'ابحث عن مادة...',
    'materials.all_categories': 'جميع الفئات',
    'materials.sort_by': 'ترتيب حسب',
    'materials.sort.name': 'الاسم',
    'materials.sort.price': 'السعر',
    'materials.sort.quantity': 'الكمية',
    'materials.grid': 'شبكة',
    'materials.map': 'خريطة',
    'materials.unit_price': 'سعر الوحدة',
    'materials.available': 'متاح',
    'materials.not_defined': 'غير محدد',
    'materials.warehouse_location': 'موقع المستودع',
    'materials.shape': 'الشكل',
    'materials.edit': 'تعديل',
    'materials.delete': 'حذف',
    'materials.deleting': 'جار الحذف...',
    'materials.none_found': 'لم يتم العثور على مواد',
    'materials.no_match': 'لا توجد مواد تطابق معايير البحث.',
    'materials.add_first': 'ابدأ بإضافة أول مادة.',
    'materials.no_geolocated': 'لا توجد مواد جغرافية',
    'materials.geolocated_hint': 'المواد ذات الإحداثيات الجغرافية ستظهر هنا.',
    'materials.map.empty_title': 'لا توجد مشاريع جغرافية',
    'materials.map.empty_desc': 'لم يتم العثور على مشاريع ذات إحداثيات جغرافية.',
    'materials.map.warehouse': 'مستودع',
    'materials.map.zone': 'منطقة',
    'materials.map.center': 'المركز',
    'materials.map.shape': 'الشكل',
    'materials.map.instructions': 'انقر لإضافة نقاط للمنطقة. انقر على "إنهاء" عند الانتهاء.',
    'materials.map.finish': 'إنهاء',
    'materials.map.clear': 'مسح',
    'materials.map.latitude': 'خط العرض',
    'materials.map.longitude': 'خط الطول',
    'materials.map.apply': 'تطبيق',
    'materials.map.drawing': 'جار الرسم...',
    'materials.map.draw.zone': 'رسم منطقة',
    'materials.map.draw.warehouse': 'رسم مستودع',
    'materials.map.shape.type': 'نوع الشكل:',
    'materials.map.shape.polygon': 'مضلع',
    'materials.map.shape.rectangle': 'مستطيل',
    'materials.map.shape.circle': 'دائرة',
    'materials.map.status.center': 'المركز',
    'materials.map.status.zone': 'تم رسم المنطقة',
    'materials.map.status.warehouse': 'تم رسم المستودع',
    'materials.map.status.points': 'نقاط',
    'project_import.title': 'Import projet',
  },
  en: {
    'projects.tab.list': 'projects',
    'projects.tab.map': 'Map',
    'language.french': "French",
    'language.english': " English",
    'language.arabic': "Arabic",
    'project_import.title': 'Import projet',
    "users.title": "User Management",
    "users.new": "New User",
    "users.search_placeholder": "Search for a user...",
    "users.table.name": "User",
    "users.table.phone": "Phone",
    "users.table.national_id": "National ID",
    "users.table.role": "Main Role",
    "users.table.status": "Status",
    "users.table.actions": "Actions",
    "users.no_results": "No user matches the search",
    "users.none_found": "No users found",
    "users.no_name": "User without name",
    "users.phone": "Phone",
    "users.national_id": "National ID",
    "users.created_at": "Registration date",
    "users.total": "Total: {count} user(s)",
    "users.details_title": "User Details",
    "users.manage_roles": "Manage roles",
    'users.created_successfully': "Employee created successfully",
    'users.deleted_successfully': "Employee deleted successfully",
    'users.created': "User created",
    'users.created_success': "The new user was created successfully.",
    'users.updated': "User updated",
    'users.updated_success': "User information has been updated.",
    'error.title': "Error",
    'error.missing_fields': "Please fill in all required fields.",
    'error.user_id_required': "User ID required.",
    'error.generic': "An error occurred.",
    'roles.assigned': "Role assigned",
    'roles.assigned_success': "Role {role} assigned successfully.",
    'roles.assign_error': "Failed to assign role.",
    'roles.removed': "Role removed",
    'roles.removed_success': "Role {role} removed successfully.",
    'roles.remove_error': "Failed to remove role.",
    'loading': "Loading...",
    'contact.title': 'Contact us',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Name',
    'contact.form.name_placeholder': 'Your name',
    'contact.form.email': 'Email',
    'contact.form.email_placeholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subject_placeholder': 'Subject of your message',
    'contact.form.message': 'Message',
    'contact.form.message_placeholder': 'Your message...',
    'contact.form.send': 'Send message',
    'contact.alert.sent': 'Your message has been sent. We will get back to you as soon as possible.',
    'contact.info.title': 'Our contact details',
    'contact.info.address': 'Address',
    'contact.info.address_value': '123 Construction Avenue\nNouakchott, Mauritania',
    'contact.info.phone': 'Phone',
    'contact.info.phone_value': '+222 45 25 25 25',
    'contact.info.email': 'Email',
    'contact.info.email_value': 'contact@materiaux-gestion.mr',
    'contact.info.hours': "Opening hours",
    'contact.info.hours_value': 'Monday - Friday: 8:00 - 17:00\nSaturday: 9:00 - 13:00\nSunday: Closed',
    'contact.info.social': 'Follow us',
    'project_create.tabs.form': 'Form',
    'project_create.tabs.materials': 'Materials',
    'project_create.tabs.map': 'Map',
    'materials.required': 'Please select at least one material',
    'project_create.materials.back_to_form': 'Back to form',
    'project_create.form.create': 'Create project',
    'project_create.from_materials': 'From materials',
    'project_create.form.add_materials': 'Add materials',
    'project.title': 'Project',
    'project.name': 'Project name',
    'project.status': 'Status',
    'project.start_date': 'Start date',
    'project.end_date': 'End date',
    'project.location': 'Location',
    'project.description': 'Description',
    'project.manager': 'Project manager',
    'project.team': 'Team',
    'project.budget': 'Budget',
    'project.progress': 'Progress',
    'project.actions': 'Actions',
    'project.edit': 'Edit project',
    'project.delete': 'Delete project',
    'project.save': 'Save',
    'project.cancel': 'Cancel',
    'project.confirm_delete': 'Are you sure you want to delete this project?',
    'project.none_found': 'No projects found',
    'project.add': 'Add project',
    'payment.title': 'Payments',
    'payment.new': 'New payment',
    'payment.amount': 'Amount',
    'payment.date': 'Payment date',
    'payment.method': 'Payment method',
    'payment.status': 'Status',
    'payment.description': 'Description',
    'payment.add': 'Add payment',
    'payment.edit': 'Edit payment',
    'payment.delete': 'Delete payment',
    'payment.confirm_delete': 'Are you sure you want to delete this payment?',
    'payment.save': 'Save',
    'payment.none_found': 'No payments found',
    'payment.success': 'Payment saved successfully',
    'payment.error': 'Error saving payment',
    "policy.title": "Privacy Policy",
    "policy.last_update": "Last update: May 16, 2025",
    "policy.section1.title": "1. Introduction",
    "policy.section1.text": "We are committed to protecting the privacy and personal data of our users. This privacy policy explains how we collect, use, disclose, and protect your information when you use our materials and project management platform.",
    "policy.section2.title": "2. Information We Collect",
    "policy.section2.text": "We collect the following types of information:",
    "policy.section2.item1": "Personal information: name, email address, phone number, national ID.",
    "policy.section2.item2": "Account information: login credentials, preferences, and settings.",
    "policy.section2.item3": "Project data: project details, materials, inspections, and payments.",
    "policy.section2.item4": "Usage information: how you interact with our platform, features used, and time spent.",
    "policy.section3.title": "3. How We Use Your Information",
    "policy.section3.text": "We use your information to:",
    "policy.section3.item1": "Provide and maintain our services.",
    "policy.section3.item2": "Improve, personalize, and develop our platform.",
    "policy.section3.item3": "Communicate with you, including sending you updates about our services.",
    "policy.section3.item4": "Ensure the security of our platform.",
    "policy.section3.item5": "Comply with legal obligations.",
    "policy.section4.title": "4. Information Sharing",
    "policy.section4.text": "We only share your personal information with:",
    "policy.section4.item1": "Members of your team or organization who have access to the same project.",
    "policy.section4.item2": "Our third-party service providers who help us operate our platform.",
    "policy.section4.item3": "Legal authorities when we are legally required to do so.",
    "policy.section5.title": "5. Data Security",
    "policy.section5.text": "We implement appropriate security measures to protect your personal information from unauthorized access, alteration, disclosure, or destruction.",
    "policy.section6.title": "6. Your Rights",
    "policy.section6.text": "You have the right to:",
    "policy.section6.item1": "Access your personal data.",
    "policy.section6.item2": "Rectify your personal data if it is inaccurate.",
    "policy.section6.item3": "Request the erasure of your personal data.",
    "policy.section6.item4": "Restrict or object to the processing of your data.",
    "policy.section6.item5": "Request the portability of your data.",
    "policy.section7.title": "7. Changes to This Policy",
    "policy.section7.text": "We may update this privacy policy periodically. We will notify you of any changes by posting the new privacy policy on this page.",
    "policy.section8.title": "8. Contact",
    "policy.section8.text": "If you have any questions regarding this privacy policy, please contact us at privacy@materiaux-gestion.mr.",
    // Navigation
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.materials': 'Materials',
    'nav.users': 'Users',
    'nav.login': 'Login',
    'nav.profile': 'Profile',

    // Documents
    'documents.title': 'Document Management',
    'documents.subtitle': 'Manage all your project documents, contracts, reports, and information',
    'documents.tabs.all': 'All',
    'documents.tabs.documents': 'Documents',
    'documents.tabs.tender': "Tenders",
    'documents.tabs.suppliers': 'Suppliers',
    'documents.tabs.tasks': 'Tasks',
    'documents.tabs.employees': 'Employees',
    'documents.tabs.upload': 'Upload',
    'documents.tabs.viewer': 'Viewer',
    'documents.type.inspection_report': "Inspection reports",
    'documents.type.location_photo': 'Location photos',
    'documents.type.project_report': 'Project reports',
    'documents.type.contract': 'Contracts',
    'documents.type.supplier_info': 'Supplier information',
    'documents.type.task_assignment': 'Task assignments',
    'documents.type.employee_record': 'Employee records',
    'documents.type.tender_documents': "Tender documents",
    'documents.card.click_to_view': 'Click to view documents of this type',
    'documents.tender.title': "Tender Documents",
    'documents.tender.select_project': 'Select a project to view its tender documents',
    'documents.tender.select_project_placeholder': 'Select a project...',
    'documents.tender.add_title': "Add Tender Document",
    'documents.tender.add_description': 'Fill out the form to add a document related to this project.',
    "task.subtitle": "Assign and track your team's tasks",
    "task.title": "Tasks",
    "task.unassigned": "Unassigned",
    "task.assignments_title": "Task Assignments",
    "task.create_sample_data": "Create sample data",
    "task.new": "New Task",
    "task.edit": "Edit Task",
    "task.select_project": "Select project",
    "task.assigned_to": "Assigned to",
    "task.select_employee": "Select employee",
    "task.due_date": "Due date",
    "task.priority": "Priority",
    "task.priority_low": "Low",
    "task.priority_medium": "Medium",
    "task.priority_high": "High",
    "task.status": "Status",
    "task.status_pending": "Pending",
    "task.status_in_progress": "In progress",
    "task.status_completed": "Completed",
    "task.status_cancelled": "Cancelled",
    "task.description": "Description",
    "task.notes": "Notes",
    "task.update": "Update",
    "task.create": "Create",
    "task.cancel": "Cancel",
    "task.due": "Due",
    "task.created": "Created",
    "task.none_found": "No tasks found",
    "task.total": "Total",
    'toast.saved_title': 'Saved',
    'toast.saved_description': 'Information saved successfully.',
    'elements.measured': 'Measured elements',
    'total.value': 'Total value',
    'total.quantity': 'Total quantity',
    'inspection.dialog.title': "Create a new inspection",
    'inspection.dialog.new_inspection': "New Inspection",
    'inspection.dialog.description': "Record the inspection details for project \"{project}\".",
    'inspection.dialog.date': "Inspection date",
    'inspection.dialog.inspector': "Inspector",
    'inspection.dialog.progress': "Project progress (%)",
    'inspection.dialog.comments': "Comments",
    'inspection.dialog.status_approved': "Approved",
    'inspection.dialog.status_pending': "Pending",
    'inspection.dialog.status_requires_changes': "Requires changes",
    'inspection.dialog.status_rejected': "Rejected",
    'projects.progress_done': 'done',
    'projects.overview.description': 'Project description',
    'project_create.title': 'Create Project',
    'project_create.name_label': 'Project name',
    'project_create.name_placeholder': 'Enter project name',
    'project_create.form.description': 'Description',
    'project_create.form.description_placeholder': 'Describe the project...',
    'project_create.form.location': 'Project location',
    'project_create.form.location_placeholder': 'City, region or address',
    'project_create.form.status': 'Project status',
    'project_create.form.status_placeholder': 'Select status',
    'project_create.status.pending': 'Pending',
    'project_create.status.ongoing': 'Ongoing',
    'project_create.status.completed': 'Completed',
    'project_create.status.suspended': 'Suspended',
    'project_create.status.cancelled': 'Cancelled',
    'project_create.form.progress': 'Project progress',
    'project_create.form.progress_placeholder': '0-100',
    'project_create.form.progress_desc': 'Indicate the project progress percentage.',
    'project_create.form.progress_current': 'Current progress',
    'project_create.form.budget': 'Project budget',
    'project_create.form.budget_placeholder': 'Amount in MRU',
    'project_create.form.budget_desc': 'Indicate the total budget planned for this project',
    'project_create.form.team_size': "Team size",
    'project_create.form.team_size_placeholder': "Number of members",
    'project_create.form.start_date': 'Project start date',
    'project_create.form.latitude': 'Latitude',
    'project_create.form.latitude_placeholder': 'Ex: 18.079052',
    'project_create.form.longitude': 'Longitude',
    'project_create.form.longitude_placeholder': 'Ex: -15.965634',
    'project_create.form.select_on_map': 'Select on map',
    'project_create.form.creating': 'Creating...',
    'project_create.map.click_hint': 'Click on the map to select the project location',
    'project_create.map.my_position': 'My position',
    'project_create.map.selected_position': 'Selected position',
    'project_create.map.latitude': 'Latitude',
    'project_create.map.longitude': 'Longitude',
    'project_create.map.back_to_form': 'Back to form',
    'project_create.back_to_projects': 'Back to project list',
    'project_create.toast.position_selected': 'Position selected',
    'project_create.toast.geolocation_error': 'Geolocation error',
    'project_create.toast.geolocation_unavailable': "Unable to get your current position.",
    'project_create.toast.geolocation_not_supported': "Geolocation not supported",
    'project_create.toast.geolocation_not_supported_desc': "Your browser does not support geolocation.",
    'project_create.toast.created': "Project created",
    'project_create.toast.created_desc': "The project \"{title}\" was created successfully.",
    'project_create.toast.error': "Error creating project",
    'project_create.toast.error_desc': "Unable to create the project. Please try again.",
    'project_create.toast.materials_error': "Error adding materials",
    'project_create.toast.materials_error_desc': "Unable to add materials to the project.",
    'terms.title': "Terms of Use",
    'terms.last_update': "Last update",
    'terms.section1.title': "1. Acceptance of Terms",
    'terms.section1.text': "By accessing and using this materials and project management platform, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use this platform.",
    'terms.section2.title': "2. Service Description",
    'terms.section2.text': "Our platform provides project and materials management tools for the construction and public works sectors. Features include project tracking, materials management, inspections, and financial tracking.",
    'terms.section3.title': "3. User Accounts",
    'terms.section3.text': "To access certain features of the platform, you must create an account. You are responsible for maintaining the confidentiality of your account information and all activities that occur under your account.",
    'terms.section4.title': "4. Appropriate Use",
    'terms.section4.text': "You agree to use the platform only for lawful purposes and in a manner that does not violate the rights of others or restrict their use of the platform.",
    'terms.section5.title': "5. Intellectual Property",
    'terms.section5.text': "All content on the platform, including text, graphics, logos, icons, and images, is the property of our company and is protected by intellectual property laws.",
    'terms.section6.title': "6. Limitation of Liability",
    'terms.section6.text': "Our company will not be liable for any direct, indirect, incidental, consequential, or punitive damages resulting from your access to or use of the platform.",
    'terms.section7.title': "7. Changes to Terms",
    'terms.section7.text': "We reserve the right to modify these terms at any time. Changes will take effect upon posting on the platform. Your continued use of the platform after changes are posted constitutes your acceptance of those changes.",
    'terms.section8.title': "8. Contact",
    'terms.section8.text': "If you have any questions regarding these terms, please contact us at support@materiaux-gestion.mr or by phone at +222 45 25 25 25.",
    // --- auth.* ---
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.remember_me': 'Remember me',
    'auth.forgot_password': 'Forgot password?',
    'auth.full_name': 'Full name',
    'auth.phone': 'Phone',
    'auth.national_id': 'National ID',
    'auth.accept_terms': 'I accept the terms of use and privacy policy',
    'auth.submit': 'Submit',
    'auth.sign_in_with_google': 'Continue with Google',
    'auth.sign_in_with_phone': 'By phone',
    'auth.sign_in_with_national_id': 'By National ID',
    'auth.or_continue_with': 'Or continue with',
    'auth.or_register_with': 'Or register with',
    'auth.create_account': 'Create account',
    'auth.welcome': 'Welcome',
    'auth.connect_to_continue': 'Sign in to continue',
    'auth.simulated_registration': 'Simulated registration',
    'auth.simulated_registration_description': 'This is a simulated registration in development mode.',
    'auth.simulated_login': 'Simulated login',
    'auth.reset_password': 'Forgot password?',
    'auth.send_code': 'Receive code',
    'auth.verify_code': 'Verify code',
    'auth.use_other_phone': 'Use another phone number',
    'auth.use_email_login': 'Back to email login',
    'auth.use_national_id_login': 'Login with National ID',
    'auth.password_requirements': 'Password must be at least 8 characters',
    'auth.terms': 'terms of use',
    'auth.privacy': 'privacy policy',
    'auth.error.invalid_credentials': 'The email or password you entered is incorrect. Please check and try again.',
    'auth.button.loading': 'Loading...',
    'auth.signup_disabled': 'Signup disabled',
    'auth.signup_disabled_description': 'Signup is currently disabled.',
    'auth.weak_password': 'Weak password',
    'auth.weak_password_description': 'Your password does not meet security requirements.',
    'auth.authentication_error': 'Authentication error',
    'auth.unexpected_error': 'An unexpected error occurred.',
    'auth.logout': 'Logout',
    'auth.menu': 'Menu',

    // --- footer.* ---
    'footer.about': 'About',
    'footer.about_desc': 'Materials and project management platform for the construction and public works sector in Mauritania. Optimize your resources, track your projects, and collaborate efficiently.',
    'footer.rights': 'All rights reserved.',
    'footer.by_hadratech': 'Developed by Hadratech',
    'footer.quick_links': 'Quick links',
    'footer.legal': 'Legal',

    // --- dashboard.* ---
    'dashboard.title': 'Dashboard',
    'dashboard.active_projects': 'Active projects',
    'dashboard.status_overview': 'Status overview',
    'dashboard.active_projects_label': 'active projects',
    'dashboard.total_budget': 'Total budget',
    'dashboard.financial_resources': 'Financial resources',
    'dashboard.team': 'Team',
    'dashboard.project_staff': 'Project staff',
    'dashboard.members': 'members',
    'dashboard.materials': 'Materials',
    'dashboard.available_resources': 'Available resources',
    'dashboard.types': 'types',
    'dashboard.project_progress': 'Project progress',
    'dashboard.no_data': 'No data available',
    'dashboard.recent_projects': 'Recent projects',
    'dashboard.view_all': 'View all',
    'dashboard.no_projects': 'No projects available',
    'dashboard.distribution_by_region': 'Distribution by region',
    'dashboard.project_distribution': 'Project distribution',
    'dashboard.no_geolocated_projects': 'No geolocated projects available',
    'dashboard.dev_mode': 'Development mode active',
    'dashboard.loading': 'Loading dashboard...',

    // --- materials.* ---
    'materials.title': 'Materials',
    'materials.new': 'New Material',
    'materials.name': 'Name',
    'materials.category': 'Category',
    'materials.price': 'Unit price',
    'materials.quantity': 'Quantity',
    'materials.unit': 'Unit',
    'materials.description': 'Description',
    'materials.address': 'Address',
    'materials.button.save': 'Save material',
    'materials.button.loading': 'Saving...',
    'materials.map.title': 'Warehouse location',
    'materials.map.description': 'Set the warehouse GPS position and draw its shape and storage area',
    'materials.toast.created': 'Material created',
    'materials.toast.created_description': 'The material "{name}" was created successfully with its location.',
    'materials.toast.error': 'Error',
    'materials.toast.error_description': 'Unable to create the material. Please try again later.',
    'materials.error.name_required': 'Material name is required',
    'materials.form.basic_info': 'Basic information',
    'materials.form.workspace_location': 'Workspace and location',
    'materials.form.quantities_pricing': 'Quantities and pricing',
    'materials.form.timeline': 'Timeline',
    'materials.form.supplier_info': 'Supplier information',
    'materials.name_placeholder': 'Ex: Portland Cement',
    'materials.description_placeholder': 'Describe the material characteristics...',
    'materials.workspace': 'Workspace',
    'materials.workspace_placeholder': 'Select a workspace',
    'materials.address_placeholder': 'Number, street name, postal code, city, country',
    'materials.available_quantity': 'Available quantity',
    'materials.min_quantity': 'Minimum quantity',
    'materials.timeline.start': 'Start date',
    'materials.timeline.end': 'End date',
    'materials.timeline.estimated_duration': 'Estimated duration (days)',
    'materials.loading': 'Loading materials...',
    'materials.error_loading': 'Error loading materials',
    'materials.retry': 'Retry',
    'materials.add': 'Add material',
    'materials.search_placeholder': 'Search for a material...',
    'materials.all_categories': 'All categories',
    'materials.sort_by': 'Sort by',
    'materials.sort.name': 'Name',
    'materials.sort.price': 'Price',
    'materials.sort.quantity': 'Quantity',
    'materials.grid': 'Grid',
    'materials.map': 'Map',
    'materials.unit_price': 'Unit price',
    'materials.available': 'Available',
    'materials.not_defined': 'Not defined',
    'materials.warehouse_location': 'Warehouse location',
    'materials.shape': 'Shape',
    'materials.edit': 'Edit',
    'materials.delete': 'Delete',
    'materials.deleting': 'Deleting...',
    'materials.none_found': 'No materials found',
    'materials.no_match': 'No materials match your search criteria.',
    'materials.add_first': 'Start by adding your first material.',
    'materials.no_geolocated': 'No geolocated materials',
    'materials.geolocated_hint': 'Materials with geographic coordinates will appear here.',
    'materials.map.empty_title': 'No geolocated projects',
    'materials.map.empty_desc': 'No projects with geographic coordinates found.',
    'materials.map.warehouse': 'Warehouse',
    'materials.map.zone': 'Zone',
    'materials.map.center': 'Center',
    'materials.map.shape': 'Shape',
    'materials.map.instructions': 'Click to add points to the zone. Click "Finish" when done.',
    'materials.map.finish': 'Finish',
    'materials.map.clear': 'Clear',
    'materials.map.latitude': 'Latitude',
    'materials.map.longitude': 'Longitude',
    'materials.map.apply': 'Apply',
    'materials.map.drawing': 'Drawing...',
    'materials.map.draw.zone': 'Draw Zone',
    'materials.map.draw.warehouse': 'Draw Warehouse',
    'materials.map.shape.type': 'Shape type:',
    'materials.map.shape.polygon': 'Polygon',
    'materials.map.shape.rectangle': 'Rectangle',
    'materials.map.shape.circle': 'Circle',
    'materials.map.status.center': 'Center',
    'materials.map.status.zone': 'Zone drawn',
    'materials.map.status.warehouse': 'Warehouse drawn',
    'materials.map.status.points': 'points',
  }
};

// Utility to check for duplicate keys in translation objects
function checkDuplicateTranslationKeys() {
  const duplicates: Record<string, string[]> = {};
  Object.entries(translations).forEach(([lang, obj]) => {
    const seen = new Set<string>();
    Object.keys(obj).forEach((key) => {
      if (seen.has(key)) {
        if (!duplicates[lang]) duplicates[lang] = [];
        duplicates[lang].push(key);
      }
      seen.add(key);
    });
  });
  if (Object.keys(duplicates).length > 0) {
    // eslint-disable-next-line no-console
    console.warn('Duplicate translation keys within a language:', duplicates);
  }
}
checkDuplicateTranslationKeys();

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['fr', 'ar', 'en'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
      updateDocumentSettings(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    updateDocumentSettings(language);
  }, [language]);

  const updateDocumentSettings = (lang: Language) => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.body.className = `lang-${lang}`;
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};


