import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de Bord',
    'nav.projects': 'Projets',
    'nav.materials': 'Matériaux',
    'nav.documents': 'Documents',
    'nav.tasks': 'Tâches',
    'nav.settings': 'Paramètres',
    'nav.users': 'Utilisateurs',

    // Language labels
    'language.french': 'Français',
    'language.arabic': 'العربية',
    'language.english': 'English',

    // Task translations
    'task.title': 'Tâches',
    'task.subtitle': 'Assignez et suivez les tâches de votre équipe',
    'task.assignments_title': 'Affectations de Tâches',
    'task.new': 'Nouvelle Tâche',
    'task.edit': 'Modifier',
    'task.create': 'Créer',
    'task.update': 'Mettre à jour',
    'task.cancel': 'Annuler',
    'task.create_sample_data': 'Créer des données d\'exemple',
    'task.assigned_to': 'Assigné à',
    'task.select_project': 'Sélectionner un projet',
    'task.select_employee': 'Sélectionner un employé',
    'task.due_date': 'Date d\'échéance',
    'task.priority': 'Priorité',
    'task.status': 'Statut',
    'task.description': 'Description',
    'task.notes': 'Notes',
    'task.priority_low': 'Faible',
    'task.priority_medium': 'Moyenne',
    'task.priority_high': 'Élevée',
    'task.status_pending': 'En attente',
    'task.status_in_progress': 'En cours',
    'task.status_completed': 'Terminé',
    'task.status_cancelled': 'Annulé',
    'task.unassigned': 'Non assigné',
    'task.due': 'Échéance',
    'task.created': 'Créé',
    'task.none_found': 'Aucune tâche trouvée',

    // Project translations
    'projects.title': 'Projets',
    'projects.subtitle': 'Gérez vos projets de construction',
    'projects.description': 'Gérez et suivez tous vos projets de construction en temps réel',
    'projects.create': 'Créer un Projet',
    'projects.edit': 'Modifier le Projet',
    'projects.delete': 'Supprimer',
    'projects.view': 'Voir',
    'projects.status': 'Statut',
    'projects.budget': 'Budget',
    'projects.progress': 'Progression',
    'projects.location': 'Localisation',
    'projects.start_date': 'Date de début',
    'projects.end_date': 'Date de fin',
    'projects.team_size': 'Taille de l\'équipe',
    'projects.description': 'Description',
    'projects.none_found': 'Aucun projet trouvé',
    'projects.loading': 'Chargement des projets...',
    'projects.save': 'Enregistrer',
    'projects.cancel': 'Annuler',
    'projects.filters': 'Filtres',
    'projects.all': 'Tous les projets',
    'projects.active': 'Projets actifs',
    'projects.completed': 'Projets terminés',
    'projects.pending': 'Projets en attente',

    // Documents translations
    'documents.title': 'Documents',
    'documents.subtitle': 'Gérez vos documents de projet',
    'documents.description': 'Organisez et gérez tous vos documents de construction',
    'documents.upload': 'Télécharger Document',
    'documents.download': 'Télécharger',
    'documents.view': 'Voir',
    'documents.edit': 'Modifier',
    'documents.delete': 'Supprimer',
    'documents.share': 'Partager',
    'documents.file_name': 'Nom du fichier',
    'documents.file_size': 'Taille du fichier',
    'documents.file_type': 'Type de fichier',
    'documents.uploaded_by': 'Téléchargé par',
    'documents.upload_date': 'Date de téléchargement',
    'documents.last_modified': 'Dernière modification',
    'documents.category': 'Catégorie',
    'documents.tags': 'Étiquettes',
    'documents.version': 'Version',
    'documents.status': 'Statut',
    'documents.approval_status': 'Statut d\'approbation',
    'documents.pending_approval': 'En attente d\'approbation',
    'documents.approved': 'Approuvé',
    'documents.rejected': 'Rejeté',
    'documents.draft': 'Brouillon',
    'documents.final': 'Final',
    'documents.search': 'Rechercher documents',
    'documents.filter_by_type': 'Filtrer par type',
    'documents.filter_by_status': 'Filtrer par statut',
    'documents.no_documents': 'Aucun document trouvé',
    'documents.loading': 'Chargement des documents...',
    'documents.upload_success': 'Document téléchargé avec succès',
    'documents.upload_error': 'Erreur lors du téléchargement',
    'documents.delete_success': 'Document supprimé avec succès',
    'documents.delete_error': 'Erreur lors de la suppression',
    'documents.type.contract': 'Contrat',
    'documents.type.invoice': 'Facture',
    'documents.type.report': 'Rapport',
    'documents.type.plan': 'Plan',
    'documents.type.specification': 'Spécification',
    'documents.type.permit': 'Permis',
    'documents.type.task_assignment': 'Affectation de Tâche',
    'documents.type.other': 'Autre',

    // Settings translations
    'settings.title': 'Paramètres',
    'settings.description': 'Configurez votre application',
    'settings.general': 'Général',
    'settings.account': 'Compte',
    'settings.security': 'Sécurité',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Confidentialité',
    'settings.language': 'Langue',
    'settings.theme': 'Thème',
    'settings.dark_mode': 'Mode sombre',
    'settings.light_mode': 'Mode clair',
    'settings.auto_mode': 'Mode automatique',
    'settings.profile': 'Profil',
    'settings.change_password': 'Changer le mot de passe',
    'settings.two_factor': 'Authentification à deux facteurs',
    'settings.email_notifications': 'Notifications par email',
    'settings.push_notifications': 'Notifications push',
    'settings.sms_notifications': 'Notifications SMS',
    'settings.backup': 'Sauvegarde',
    'settings.export_data': 'Exporter les données',
    'settings.import_data': 'Importer les données',
    'settings.system': 'Système',
    'settings.database': 'Base de données',
    'settings.storage': 'Stockage',
    'settings.api': 'API',
    'settings.integrations': 'Intégrations',
    'settings.advanced': 'Avancé',
    'settings.reset': 'Réinitialiser',
    'settings.restore_defaults': 'Restaurer les paramètres par défaut',
    'settings.save_changes': 'Enregistrer les modifications',
    'settings.discard_changes': 'Annuler les modifications',
    'settings.changes_saved': 'Modifications enregistrées',
    'settings.error_saving': 'Erreur lors de l\'enregistrement',
    'settings.tabs.database': 'Base de données',
    'settings.tabs.storage': 'Stockage',
    'settings.tabs.keycloak': 'Keycloak',
    'settings.tabs.keycloak_config': 'Config Keycloak',
    'settings.tabs.system': 'Système',
    'settings.dev_mode_active': 'Mode Développement Actif',
    'settings.dev_mode_desc': 'Le mode développement est actuellement activé pour les tests.',
    'settings.current_role': 'Rôle actuel',
    'settings.dev_role_updated': 'Rôle de développement mis à jour',
    'settings.dev_role_changed': 'Rôle changé vers {role}',
    'settings.system.title': 'Paramètres Système',
    'settings.system.desc': 'Configuration système avancée',
    'settings.system.coming_soon': 'Fonctionnalités à venir...',

    // Common
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.status': 'Statut',
    'common.priority': 'Priorité',
    'common.description': 'Description',
    'common.notes': 'Notes',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'common.warning': 'Attention',
    'common.info': 'Information',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.close': 'Fermer',
    'common.open': 'Ouvrir',
    'common.new': 'Nouveau',
    'common.create': 'Créer',
    'common.update': 'Mettre à jour',
    'common.refresh': 'Actualiser',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.submit': 'Soumettre',
    'common.reset': 'Réinitialiser',

    // Locale
    'locale': 'fr-FR'
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة القيادة',
    'nav.projects': 'المشاريع',
    'nav.materials': 'المواد',
    'nav.documents': 'الوثائق',
    'nav.tasks': 'المهام',
    'nav.settings': 'الإعدادات',
    'nav.users': 'المستخدمون',

    // Language labels
    'language.french': 'Français',
    'language.arabic': 'العربية',
    'language.english': 'English',

    // Task translations
    'task.title': 'المهام',
    'task.subtitle': 'قم بتعيين ومتابعة مهام فريقك',
    'task.assignments_title': 'تكليفات المهام',
    'task.new': 'مهمة جديدة',
    'task.edit': 'تعديل',
    'task.create': 'إنشاء',
    'task.update': 'تحديث',
    'task.cancel': 'إلغاء',
    'task.create_sample_data': 'إنشاء بيانات تجريبية',
    'task.assigned_to': 'مُكلف إلى',
    'task.select_project': 'اختر مشروعاً',
    'task.select_employee': 'اختر موظفاً',
    'task.due_date': 'تاريخ الاستحقاق',
    'task.priority': 'الأولوية',
    'task.status': 'الحالة',
    'task.description': 'الوصف',
    'task.notes': 'ملاحظات',
    'task.priority_low': 'منخفضة',
    'task.priority_medium': 'متوسطة',
    'task.priority_high': 'عالية',
    'task.status_pending': 'في الانتظار',
    'task.status_in_progress': 'قيد التنفيذ',
    'task.status_completed': 'مكتملة',
    'task.status_cancelled': 'ملغية',
    'task.unassigned': 'غير مُكلف',
    'task.due': 'الاستحقاق',
    'task.created': 'تم الإنشاء',
    'task.none_found': 'لم يتم العثور على مهام',

    // Project translations
    'projects.title': 'المشاريع',
    'projects.subtitle': 'إدارة مشاريع البناء الخاصة بك',
    'projects.description': 'إدارة ومتابعة جميع مشاريع البناء الخاصة بك في الوقت الفعلي',
    'projects.create': 'إنشاء مشروع',
    'projects.edit': 'تعديل المشروع',
    'projects.delete': 'حذف',
    'projects.view': 'عرض',
    'projects.status': 'الحالة',
    'projects.budget': 'الميزانية',
    'projects.progress': 'التقدم',
    'projects.location': 'الموقع',
    'projects.start_date': 'تاريخ البداية',
    'projects.end_date': 'تاريخ النهاية',
    'projects.team_size': 'حجم الفريق',
    'projects.description': 'الوصف',
    'projects.none_found': 'لم يتم العثور على مشاريع',
    'projects.loading': 'جاري تحميل المشاريع...',
    'projects.save': 'حفظ',
    'projects.cancel': 'إلغاء',
    'projects.filters': 'المرشحات',
    'projects.all': 'جميع المشاريع',
    'projects.active': 'المشاريع النشطة',
    'projects.completed': 'المشاريع المكتملة',
    'projects.pending': 'المشاريع المعلقة',

    // Documents translations
    'documents.title': 'الوثائق',
    'documents.subtitle': 'إدارة وثائق المشروع',
    'documents.description': 'تنظيم وإدارة جميع وثائق البناء الخاصة بك',
    'documents.upload': 'رفع وثيقة',
    'documents.download': 'تحميل',
    'documents.view': 'عرض',
    'documents.edit': 'تعديل',
    'documents.delete': 'حذف',
    'documents.share': 'مشاركة',
    'documents.file_name': 'اسم الملف',
    'documents.file_size': 'حجم الملف',
    'documents.file_type': 'نوع الملف',
    'documents.uploaded_by': 'رفع بواسطة',
    'documents.upload_date': 'تاريخ الرفع',
    'documents.last_modified': 'آخر تعديل',
    'documents.category': 'الفئة',
    'documents.tags': 'العلامات',
    'documents.version': 'الإصدار',
    'documents.status': 'الحالة',
    'documents.approval_status': 'حالة الموافقة',
    'documents.pending_approval': 'في انتظار الموافقة',
    'documents.approved': 'موافق عليه',
    'documents.rejected': 'مرفوض',
    'documents.draft': 'مسودة',
    'documents.final': 'نهائي',
    'documents.search': 'البحث في الوثائق',
    'documents.filter_by_type': 'تصفية حسب النوع',
    'documents.filter_by_status': 'تصفية حسب الحالة',
    'documents.no_documents': 'لم يتم العثور على وثائق',
    'documents.loading': 'جاري تحميل الوثائق...',
    'documents.upload_success': 'تم رفع الوثيقة بنجاح',
    'documents.upload_error': 'خطأ في رفع الوثيقة',
    'documents.delete_success': 'تم حذف الوثيقة بنجاح',
    'documents.delete_error': 'خطأ في حذف الوثيقة',
    'documents.type.contract': 'عقد',
    'documents.type.invoice': 'فاتورة',
    'documents.type.report': 'تقرير',
    'documents.type.plan': 'مخطط',
    'documents.type.specification': 'مواصفات',
    'documents.type.permit': 'تصريح',
    'documents.type.task_assignment': 'تكليف مهمة',
    'documents.type.other': 'أخرى',

    // Settings translations
    'settings.title': 'الإعدادات',
    'settings.description': 'قم بتكوين تطبيقك',
    'settings.general': 'عام',
    'settings.account': 'الحساب',
    'settings.security': 'الأمان',
    'settings.notifications': 'الإشعارات',
    'settings.privacy': 'الخصوصية',
    'settings.language': 'اللغة',
    'settings.theme': 'المظهر',
    'settings.dark_mode': 'الوضع الداكن',
    'settings.light_mode': 'الوضع الفاتح',
    'settings.auto_mode': 'الوضع التلقائي',
    'settings.profile': 'الملف الشخصي',
    'settings.change_password': 'تغيير كلمة المرور',
    'settings.two_factor': 'المصادقة الثنائية',
    'settings.email_notifications': 'إشعارات البريد الإلكتروني',
    'settings.push_notifications': 'الإشعارات الفورية',
    'settings.sms_notifications': 'إشعارات الرسائل النصية',
    'settings.backup': 'النسخ الاحتياطي',
    'settings.export_data': 'تصدير البيانات',
    'settings.import_data': 'استيراد البيانات',
    'settings.system': 'النظام',
    'settings.database': 'قاعدة البيانات',
    'settings.storage': 'التخزين',
    'settings.api': 'واجهة برمجة التطبيقات',
    'settings.integrations': 'التكاملات',
    'settings.advanced': 'متقدم',
    'settings.reset': 'إعادة تعيين',
    'settings.restore_defaults': 'استعادة الإعدادات الافتراضية',
    'settings.save_changes': 'حفظ التغييرات',
    'settings.discard_changes': 'تجاهل التغييرات',
    'settings.changes_saved': 'تم حفظ التغييرات',
    'settings.error_saving': 'خطأ في الحفظ',
    'settings.tabs.database': 'قاعدة البيانات',
    'settings.tabs.storage': 'التخزين',
    'settings.tabs.keycloak': 'Keycloak',
    'settings.tabs.keycloak_config': 'تكوين Keycloak',
    'settings.tabs.system': 'النظام',
    'settings.dev_mode_active': 'وضع التطوير نشط',
    'settings.dev_mode_desc': 'وضع التطوير نشط حالياً للاختبار.',
    'settings.current_role': 'الدور الحالي',
    'settings.dev_role_updated': 'تم تحديث دور التطوير',
    'settings.dev_role_changed': 'تم تغيير الدور إلى {role}',
    'settings.system.title': 'إعدادات النظام',
    'settings.system.desc': 'تكوين النظام المتقدم',
    'settings.system.coming_soon': 'ميزات قادمة...',

    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.actions': 'الإجراءات',
    'common.date': 'التاريخ',
    'common.status': 'الحالة',
    'common.priority': 'الأولوية',
    'common.description': 'الوصف',
    'common.notes': 'ملاحظات',
    'common.success': 'نجح',
    'common.error': 'خطأ',
    'common.warning': 'تحذير',
    'common.info': 'معلومات',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.new': 'جديد',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.refresh': 'تحديث',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',

    // Locale
    'locale': 'ar-AR'
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.projects': 'Projects',
    'nav.materials': 'Materials',
    'nav.documents': 'Documents',
    'nav.tasks': 'Tasks',
    'nav.settings': 'Settings',
    'nav.users': 'Users',

    // Language labels
    'language.french': 'Français',
    'language.arabic': 'العربية',
    'language.english': 'English',

    // Task translations
    'task.title': 'Tasks',
    'task.subtitle': 'Assign and track your team\'s tasks',
    'task.assignments_title': 'Task Assignments',
    'task.new': 'New Task',
    'task.edit': 'Edit',
    'task.create': 'Create',
    'task.update': 'Update',
    'task.cancel': 'Cancel',
    'task.create_sample_data': 'Create Sample Data',
    'task.assigned_to': 'Assigned to',
    'task.select_project': 'Select a project',
    'task.select_employee': 'Select an employee',
    'task.due_date': 'Due Date',
    'task.priority': 'Priority',
    'task.status': 'Status',
    'task.description': 'Description',
    'task.notes': 'Notes',
    'task.priority_low': 'Low',
    'task.priority_medium': 'Medium',
    'task.priority_high': 'High',
    'task.status_pending': 'Pending',
    'task.status_in_progress': 'In Progress',
    'task.status_completed': 'Completed',
    'task.status_cancelled': 'Cancelled',
    'task.unassigned': 'Unassigned',
    'task.due': 'Due',
    'task.created': 'Created',
    'task.none_found': 'No tasks found',

    // Project translations
    'projects.title': 'Projects',
    'projects.subtitle': 'Manage your construction projects',
    'projects.description': 'Manage and track all your construction projects in real-time',
    'projects.create': 'Create Project',
    'projects.edit': 'Edit Project',
    'projects.delete': 'Delete',
    'projects.view': 'View',
    'projects.status': 'Status',
    'projects.budget': 'Budget',
    'projects.progress': 'Progress',
    'projects.location': 'Location',
    'projects.start_date': 'Start Date',
    'projects.end_date': 'End Date',
    'projects.team_size': 'Team Size',
    'projects.description': 'Description',
    'projects.none_found': 'No projects found',
    'projects.loading': 'Loading projects...',
    'projects.save': 'Save',
    'projects.cancel': 'Cancel',
    'projects.filters': 'Filters',
    'projects.all': 'All projects',
    'projects.active': 'Active projects',
    'projects.completed': 'Completed projects',
    'projects.pending': 'Pending projects',

    // Documents translations
    'documents.title': 'Documents',
    'documents.subtitle': 'Manage your project documents',
    'documents.description': 'Organize and manage all your construction documents',
    'documents.upload': 'Upload Document',
    'documents.download': 'Download',
    'documents.view': 'View',
    'documents.edit': 'Edit',
    'documents.delete': 'Delete',
    'documents.share': 'Share',
    'documents.file_name': 'File Name',
    'documents.file_size': 'File Size',
    'documents.file_type': 'File Type',
    'documents.uploaded_by': 'Uploaded By',
    'documents.upload_date': 'Upload Date',
    'documents.last_modified': 'Last Modified',
    'documents.category': 'Category',
    'documents.tags': 'Tags',
    'documents.version': 'Version',
    'documents.status': 'Status',
    'documents.approval_status': 'Approval Status',
    'documents.pending_approval': 'Pending Approval',
    'documents.approved': 'Approved',
    'documents.rejected': 'Rejected',
    'documents.draft': 'Draft',
    'documents.final': 'Final',
    'documents.search': 'Search documents',
    'documents.filter_by_type': 'Filter by type',
    'documents.filter_by_status': 'Filter by status',
    'documents.no_documents': 'No documents found',
    'documents.loading': 'Loading documents...',
    'documents.upload_success': 'Document uploaded successfully',
    'documents.upload_error': 'Error uploading document',
    'documents.delete_success': 'Document deleted successfully',
    'documents.delete_error': 'Error deleting document',
    'documents.type.contract': 'Contract',
    'documents.type.invoice': 'Invoice',
    'documents.type.report': 'Report',
    'documents.type.plan': 'Plan',
    'documents.type.specification': 'Specification',
    'documents.type.permit': 'Permit',
    'documents.type.task_assignment': 'Task Assignment',
    'documents.type.other': 'Other',

    // Settings translations
    'settings.title': 'Settings',
    'settings.description': 'Configure your application',
    'settings.general': 'General',
    'settings.account': 'Account',
    'settings.security': 'Security',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.dark_mode': 'Dark Mode',
    'settings.light_mode': 'Light Mode',
    'settings.auto_mode': 'Auto Mode',
    'settings.profile': 'Profile',
    'settings.change_password': 'Change Password',
    'settings.two_factor': 'Two-Factor Authentication',
    'settings.email_notifications': 'Email Notifications',
    'settings.push_notifications': 'Push Notifications',
    'settings.sms_notifications': 'SMS Notifications',
    'settings.backup': 'Backup',
    'settings.export_data': 'Export Data',
    'settings.import_data': 'Import Data',
    'settings.system': 'System',
    'settings.database': 'Database',
    'settings.storage': 'Storage',
    'settings.api': 'API',
    'settings.integrations': 'Integrations',
    'settings.advanced': 'Advanced',
    'settings.reset': 'Reset',
    'settings.restore_defaults': 'Restore Defaults',
    'settings.save_changes': 'Save Changes',
    'settings.discard_changes': 'Discard Changes',
    'settings.changes_saved': 'Changes Saved',
    'settings.error_saving': 'Error Saving',
    'settings.tabs.database': 'Database',
    'settings.tabs.storage': 'Storage',
    'settings.tabs.keycloak': 'Keycloak',
    'settings.tabs.keycloak_config': 'Keycloak Config',
    'settings.tabs.system': 'System',
    'settings.dev_mode_active': 'Development Mode Active',
    'settings.dev_mode_desc': 'Development mode is currently active for testing.',
    'settings.current_role': 'Current Role',
    'settings.dev_role_updated': 'Development role updated',
    'settings.dev_role_changed': 'Role changed to {role}',
    'settings.system.title': 'System Settings',
    'settings.system.desc': 'Advanced system configuration',
    'settings.system.coming_soon': 'Coming soon...',

    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.status': 'Status',
    'common.priority': 'Priority',
    'common.description': 'Description',
    'common.notes': 'Notes',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.new': 'New',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.refresh': 'Refresh',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',

    // Locale
    'locale': 'en-US'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
