/**
 * Tender Domain Transformer
 * Handles conversion between Tender entity and TenderDTO
 * Following hexagonal architecture principles
 */

import { Tender } from '@/domain/entities/Tender';
import { TenderDTO, TenderCreateDTO, TenderUpdateDTO, TenderListDTO, TenderSummaryDTO } from '@/dtos/entities/TenderDTO';
import { TenderStatus, SelectionMode, MarketType, EvaluationCriteria } from '@/domain/entities/Tender';

export class TenderDomainTransformer {
  /**
   * Transform Tender entity to TenderDTO
   * Entity has 20 constructor params; DTO has extra fields that don't exist on entity.
   * Map only what the entity exposes.
   */
  static toDTO(entity: Tender): TenderDTO {
    return {
      id: entity.id,
      projectId: entity.projectId,
      title: entity.title,
      description: entity.description,
      tenderNumber: entity.tenderNumber,
      status: entity.status,
      selectionMode: entity.selectionMode,
      marketType: entity.marketType,
      financingSource: entity.financingSource,
      projectReference: entity.projectReference,
      publicationDate: entity.publicationDate,
      deadlineDate: entity.deadlineDate,
      submissionDeadline: entity.deadlineDate,
      launchDate: entity.launchDate,
      attributionDate: entity.attributionDate,
      budgetMin: entity.budgetMin,
      budgetMax: entity.budgetMax,
      // Fields not on entity — default to null
      estimatedValue: null,
      contractDuration: null,
      evaluationCriteria: entity.evaluationCriteria,
      eligibilityRequirements: entity.eligibilityRequirements,
      evaluationDeadline: null,
      awardCriteria: null,
      currentPhase: null,
      currentStage: null,
      tenderCategory: null,
      procurementType: null,
      weight: null,
      // BaseEntityDTO fields
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
    };
  }

  /**
   * Transform TenderDTO to Tender entity (20 constructor args)
   */
  static fromDTO(dto: TenderDTO): Tender {
    return Tender.create({
      id: dto.id,
      projectId: dto.projectId || undefined,
      title: dto.title,
      description: dto.description || undefined,
      tenderNumber: dto.tenderNumber || undefined,
      selectionMode: dto.selectionMode || undefined,
      marketType: dto.marketType || undefined,
      deadlineDate: dto.deadlineDate || undefined,
      budgetMin: dto.budgetMin || undefined,
      budgetMax: dto.budgetMax || undefined
    });
  }

  /**
   * Transform TenderCreateDTO to Tender entity
   */
  static fromCreateDTO(dto: TenderCreateDTO): Tender {
    return Tender.create({
      id: '', // Will be generated by repository
      projectId: dto.projectId || undefined,
      title: dto.title,
      description: dto.description || undefined,
      tenderNumber: dto.tenderNumber || undefined,
      selectionMode: dto.selectionMode || undefined,
      marketType: dto.marketType || undefined,
      deadlineDate: dto.deadlineDate || undefined,
      budgetMin: dto.budgetMin || undefined,
      budgetMax: dto.budgetMax || undefined
    });
  }

  /**
   * Transform Tender entity to TenderListDTO
   */
  static toListDTO(entity: Tender): TenderListDTO {
    return {
      id: entity.id,
      title: entity.title,
      status: entity.status,
      selectionMode: entity.selectionMode,
      marketType: entity.marketType,
      deadlineDate: entity.deadlineDate,
      budgetMin: entity.budgetMin,
      budgetMax: entity.budgetMax,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
    };
  }

  /**
   * Transform Tender entity to TenderSummaryDTO
   */
  static toSummaryDTO(entity: Tender): TenderSummaryDTO {
    return {
      id: entity.id,
      title: entity.title,
      status: entity.status,
      deadlineDate: entity.deadlineDate,
      daysUntilDeadline: entity.getDaysUntilDeadline(),
      isOverdue: entity.isDeadlinePassed(),
      budgetRange: entity.getBudgetRange(),
      submissionCount: 0,
      createdAt: entity.createdAt,
    };
  }

  /**
   * Transform Tender entity to TenderUpdateDTO
   * null → undefined conversion for optional DTO fields
   */
  static toUpdateDTO(entity: Tender): TenderUpdateDTO {
    return {
      title: entity.title,
      description: entity.description ?? undefined,
      status: entity.status,
      selectionMode: entity.selectionMode ?? undefined,
      marketType: entity.marketType ?? undefined,
      financingSource: entity.financingSource ?? undefined,
      projectReference: entity.projectReference ?? undefined,
      publicationDate: entity.publicationDate ?? undefined,
      deadlineDate: entity.deadlineDate ?? undefined,
      submissionDeadline: entity.deadlineDate ?? undefined,
      launchDate: entity.launchDate ?? undefined,
      attributionDate: entity.attributionDate ?? undefined,
      budgetMin: entity.budgetMin ?? undefined,
      budgetMax: entity.budgetMax ?? undefined,
      evaluationCriteria: entity.evaluationCriteria,
      eligibilityRequirements: entity.eligibilityRequirements,
    };
  }

  static toResponseDto(entity: Tender): TenderDTO {
    return this.toDTO(entity);
  }

  static toEntity(dto: TenderDTO): Tender {
    return this.fromDTO(dto);
  }

  static toEntityFromCreate(dto: TenderCreateDTO): Tender {
    return this.fromCreateDTO(dto);
  }

  /**
   * Transform TenderUpdateDTO to Tender entity (merge with existing)
   */
  static toEntityFromUpdate(id: string, dto: TenderUpdateDTO, existingEntity: Tender): Tender {
    return new Tender(
      id,
      existingEntity.projectId,
      dto.title ?? existingEntity.title,
      dto.description ?? existingEntity.description,
      existingEntity.tenderNumber,
      dto.status ?? existingEntity.status,
      dto.selectionMode ?? existingEntity.selectionMode,
      dto.marketType ?? existingEntity.marketType,
      dto.financingSource ?? existingEntity.financingSource,
      dto.projectReference ?? existingEntity.projectReference,
      dto.publicationDate ?? existingEntity.publicationDate,
      dto.deadlineDate ?? existingEntity.deadlineDate,
      dto.launchDate ?? existingEntity.launchDate,
      dto.attributionDate ?? existingEntity.attributionDate,
      dto.budgetMin ?? existingEntity.budgetMin,
      dto.budgetMax ?? existingEntity.budgetMax,
      dto.evaluationCriteria ?? existingEntity.evaluationCriteria,
      dto.eligibilityRequirements ?? existingEntity.eligibilityRequirements,
      existingEntity.createdAt,
      new Date().toISOString()
    );
  }
}
