/**
 * Tender Domain Transformer
 * Handles conversion between Tender entity and TenderDTO
 * Following hexagonal architecture principles
 */

import { Tender } from '@/domain/entities/Tender';
import { TenderDTO, TenderCreateDTO, TenderUpdateDTO, TenderListDTO, TenderSummaryDTO } from '@/dtos/entities/TenderDTO';
import { TenderStatus, SelectionMode, MarketType, EvaluationCriteria } from '@/domain/entities/Tender';

export class TenderDomainTransformer {
  /**
   * Transform Tender entity to TenderDTO
   * Converts Date objects to ISO strings
   */
  static toDTO(entity: Tender): TenderDTO {
    return {
      id: entity.id,
      projectId: entity.projectId,
      title: entity.title,
      description: entity.description,
      tenderNumber: entity.tenderNumber,
      status: entity.status,
      selectionMode: entity.selectionMode,
      marketType: entity.marketType,
      financingSource: entity.financingSource,
      projectReference: entity.projectReference,
      publicationDate: entity.publicationDate,
      deadlineDate: entity.deadlineDate,
      submissionDeadline: entity.deadlineDate,
      launchDate: entity.launchDate,
      attributionDate: entity.attributionDate,
      budgetMin: entity.budgetMin,
      budgetMax: entity.budgetMax,
      estimatedValue: entity.estimatedValue,
      contractDuration: entity.contractDuration,
      evaluationCriteria: entity.evaluationCriteria,
      eligibilityRequirements: entity.eligibilityRequirements,
      evaluationDeadline: entity.evaluationDeadline,
      awardCriteria: entity.awardCriteria,
      currentPhase: entity.currentPhase,
      currentStage: entity.currentStage,
      tenderCategory: entity.tenderCategory,
      procurementType: entity.procurementType,
      weight: entity.weight,
      // BaseEntityDTO fields
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
    };
  }

  /**
   * Transform TenderDTO to Tender entity
   * Converts ISO strings to Date objects
   */
  static fromDTO(dto: TenderDTO): Tender {
    return new Tender(
      dto.id,
      dto.projectId,
      dto.title,
      dto.description,
      dto.tenderNumber,
      dto.status,
      dto.selectionMode,
      dto.marketType,
      dto.financingSource,
      dto.projectReference,
      dto.publicationDate,
      dto.deadlineDate,
      dto.submissionDeadline,
      dto.launchDate,
      dto.attributionDate,
      dto.budgetMin,
      dto.budgetMax,
      dto.evaluationCriteria,
      dto.eligibilityRequirements,
      dto.evaluationDeadline,
      dto.awardCriteria,
      dto.currentPhase,
      dto.currentStage,
      dto.tenderCategory,
      dto.procurementType,
      dto.contractDuration,
      dto.createdAt,
      dto.updatedAt
    );
  }

  /**
   * Transform TenderCreateDTO to Tender entity
   * Used for creating new tenders
   */
  static fromCreateDTO(dto: TenderCreateDTO): Tender {
    const now = new Date().toISOString();
    return new Tender(
      '', // Will be generated by repository
      dto.projectId || null,
      dto.title,
      dto.description || null,
      dto.tenderNumber || null,
      'draft',
      dto.selectionMode || null,
      dto.marketType || null,
      null,
      null,
      null,
      dto.deadlineDate || null,
      dto.deadlineDate || null,
      dto.launchDate || null,
      null,
      dto.budgetMin || null,
      dto.budgetMax || null,
      dto.evaluationCriteria || [],
      dto.eligibilityRequirements || [],
      null,
      dto.awardCriteria || null,
      null,
      null,
      dto.tenderCategory || null,
      dto.procurementType || null,
      null,
      now,
      now
    );
  }

  /**
   * Transform Tender entity to TenderListDTO
   * Used for list views with limited data
   */
  static toListDTO(entity: Tender): TenderListDTO {
    return {
      id: entity.id,
      title: entity.title,
      status: entity.status,
      selectionMode: entity.selectionMode,
      marketType: entity.marketType,
      deadlineDate: entity.deadlineDate,
      budgetMin: entity.budgetMin,
      budgetMax: entity.budgetMax,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
    };
  }

  /**
   * Transform Tender entity to TenderSummaryDTO
   * Used for dashboard summaries
   */
  static toSummaryDTO(entity: Tender): TenderSummaryDTO {
    return {
      id: entity.id,
      title: entity.title,
      status: entity.status,
      deadlineDate: entity.deadlineDate,
      daysUntilDeadline: entity.getDaysUntilDeadline(),
      isOverdue: entity.isDeadlinePassed(),
      budgetRange: entity.getBudgetRange(),
      submissionCount: 0, // Would be calculated from repository
      createdAt: entity.createdAt,
    };
  }

  /**
   * Transform Tender entity to TenderUpdateDTO
   * Used for partial updates
   */
  static toUpdateDTO(entity: Tender): TenderUpdateDTO {
    return {
      title: entity.title,
      description: entity.description,
      status: entity.status,
      selectionMode: entity.selectionMode,
      marketType: entity.marketType,
      financingSource: entity.financingSource,
      projectReference: entity.projectReference,
      publicationDate: entity.publicationDate,
      deadlineDate: entity.deadlineDate,
      submissionDeadline: entity.deadlineDate,
      launchDate: entity.launchDate,
      attributionDate: entity.attributionDate,
      budgetMin: entity.budgetMin,
      budgetMax: entity.budgetMax,
      estimatedValue: entity.estimatedValue,
      contractDuration: entity.contractDuration,
      evaluationCriteria: entity.evaluationCriteria,
      eligibilityRequirements: entity.eligibilityRequirements,
      evaluationDeadline: entity.evaluationDeadline,
      awardCriteria: entity.awardCriteria,
      currentPhase: entity.currentPhase,
      currentStage: entity.currentStage,
      tenderCategory: entity.tenderCategory,
      procurementType: entity.procurementType,
      weight: entity.weight,
    };
  }

  /**
   * Transform Tender entity to TenderDTO (alias for toDTO)
   */
  static toResponseDto(entity: Tender): TenderDTO {
    return this.toDTO(entity);
  }

  /**
   * Transform TenderDTO to Tender entity (alias for fromDTO)
   */
  static toEntity(dto: TenderDTO): Tender {
    return this.fromDTO(dto);
  }

  /**
   * Transform TenderCreateDTO to Tender entity (alias for fromCreateDTO)
   */
  static toEntityFromCreate(dto: TenderCreateDTO): Tender {
    return this.fromCreateDTO(dto);
  }

  /**
   * Transform TenderUpdateDTO to Tender entity
   * Used for partial updates
   */
  static toEntityFromUpdate(id: string, dto: TenderUpdateDTO, existingEntity: Tender): Tender {
    return new Tender(
      id,
      existingEntity.projectId,
      dto.title ?? existingEntity.title,
      dto.description ?? existingEntity.description,
      existingEntity.tenderNumber,
      dto.status ?? existingEntity.status,
      dto.selectionMode ?? existingEntity.selectionMode,
      dto.marketType ?? existingEntity.marketType,
      dto.financingSource ?? existingEntity.financingSource,
      dto.projectReference ?? existingEntity.projectReference,
      dto.publicationDate ?? existingEntity.publicationDate,
      dto.deadlineDate ?? existingEntity.deadlineDate,
      dto.submissionDeadline ?? existingEntity.submissionDeadline,
      dto.launchDate ?? existingEntity.launchDate,
      dto.attributionDate ?? existingEntity.attributionDate,
      dto.budgetMin ?? existingEntity.budgetMin,
      dto.budgetMax ?? existingEntity.budgetMax,
      dto.evaluationCriteria ?? existingEntity.evaluationCriteria,
      dto.eligibilityRequirements ?? existingEntity.eligibilityRequirements,
      dto.evaluationDeadline ?? existingEntity.evaluationDeadline,
      dto.awardCriteria ?? existingEntity.awardCriteria,
      dto.currentPhase ?? existingEntity.currentPhase,
      dto.currentStage ?? existingEntity.currentStage,
      dto.tenderCategory ?? existingEntity.tenderCategory,
      dto.procurementType ?? existingEntity.procurementType,
      dto.contractDuration ?? existingEntity.contractDuration,
      existingEntity.createdAt,
      new Date().toISOString()
    );
  }
}
