/**
 * Hexagonal hooks for Tender Quantitative Estimate
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { RepositoryFactory } from '@/infrastructure/supabase/RepositoryFactory';
import { TenderEstimateService } from '@/application/services/TenderEstimateService';
import { MaterialService } from '@/application/services/MaterialService';
import { TenderEstimate } from '@/domain/entities/TenderEstimate';
import { TenderEstimateDTO, TenderEstimateItemDTO } from '@/dtos/entities/TenderEstimateDTO';
import { EstimateItem, EstimateData } from '@/dtos/transforms/shared';

// Hooks
export function useTenderEstimatesHex(tenderId: string) {
  const tenderEstimateService = new TenderEstimateService();

  return useQuery({
    queryKey: ['tender-estimates', tenderId],
    queryFn: async (): Promise<TenderEstimate[]> => {
      return await tenderEstimateService.getTenderEstimates(tenderId);
    },
  });
}

export type { EstimateItem } from '@/dtos/transforms/shared';
export type { TenderEstimate } from '@/domain/entities/TenderEstimate';

export function useEstimateItemsHex(estimateId: string | null) {
  const tenderEstimateService = new TenderEstimateService();

  return useQuery({
    queryKey: ['estimate-items', estimateId],
    queryFn: async () => {
      if (!estimateId) return [];
      return await tenderEstimateService.getTenderEstimatesByTender(estimateId);
    },
    enabled: !!estimateId
  });
}

export function useMaterialsForEstimateHex() {
  const materialService = new MaterialService(RepositoryFactory.getMaterialRepository());

  return useQuery({
    queryKey: ['materials'],
    queryFn: async (): Promise<TenderEstimateItemDTO[]> => {
      const materials = await materialService.getAllMaterials();
      // Transform MaterialDTO to TenderEstimateItemDTO for compatibility
      return materials.map(material => ({
        id: material.id,
        estimate_id: '', // Will be set when used in estimate context
        material_id: material.id,
        item_code: material.name || '',
        description: material.description || '',
        unit: material.unit || '',
        quantity: 0, // Will be set when used in estimate context
        unit_price: material.pricePerUnit || 0,
        total_price: 0, // Will be calculated when used in estimate context
        category: material.category || '',
        specifications: material.specifications || '',
        item_type: 'material',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      }));
    }
  });
}

export function useParsedInvoicesHex(tenderId: string) {
  return useQuery({
    queryKey: ['parsed-invoices', tenderId],
    queryFn: async () => {
      // Implemented: Use InvoiceService following hexagonal architecture
      const { InvoiceService } = await import('@/application/services/InvoiceService');
      const { RepositoryFactory } = await import('@/infrastructure/supabase/RepositoryFactory');
      
      const invoiceRepository = RepositoryFactory.getParsedInvoiceRepository();
      const invoiceService = new InvoiceService(invoiceRepository);
      
      // Get invoices for the tender's supplier
      // For now, return all parsed invoices (could be filtered by supplier in future)
      return await invoiceService.getParsedInvoices('all');
    }
  });
}

export function useAddEstimateItemHex(estimateId: string | null) {
  const queryClient = useQueryClient();
  const tenderEstimateService = new TenderEstimateService();

  return useMutation({
    mutationFn: async (item: EstimateItem & { estimate_id: string }) => {
      // Transform EstimateItem to TenderEstimateItemDTO
      const tenderEstimateItem: TenderEstimateItemDTO = {
        id: '', // Will be generated by service
        estimate_id: item.estimate_id,
        material_id: item.material_id || undefined,
        item_code: item.material_id || '',
        description: item.description || '',
        unit: 'unit', // Default unit since EstimateItem doesn't have unit property
        quantity: item.quantity,
        unit_price: item.unit_price,
        total_price: item.total_price,
        category: item.item_type || 'material',
        specifications: '',
        item_type: item.item_type || 'material',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      };

      return await tenderEstimateService.createTenderEstimateItem(tenderEstimateItem);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['estimate-items', estimateId] });
    }
  });
}

export function useCreateInvoiceHex(tenderId: string) {
  const queryClient = useQueryClient();
  const tenderEstimateService = new TenderEstimateService();

  return useMutation({
    mutationFn: async () => {
      // ✅ Implemented invoice creation in TenderEstimateService
      return await tenderEstimateService.createInvoiceFromEstimate(tenderId);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['parsed-invoices', tenderId] });
    }
  });
}
