ALTER TABLE btp.projects
ADD COLUMN IF NOT EXISTS referential_code text;

CREATE OR REPLACE VIEW public.project_phases AS
SELECT
  project_phases.id,
  project_phases.project_id,
  project_phases.phase_name,
  project_phases.phase_type,
  project_phases.start_date,
  project_phases.end_date,
  project_phases.status,
  project_phases.progress,
  project_phases.description,
  project_phases.estimated_cost,
  project_phases.actual_cost,
  project_phases.dependencies,
  project_phases.milestones,
  project_phases.created_at,
  project_phases.updated_at,
  project_phases.created_by,
  project_phases.estimated_duration,
  project_phases.notes,
  project_phases.construction_phase,
  project_phases.construction_stage,
  project_phases.custom_phase_data,
  project_phases.materials,
  project_phases.human_resources,
  project_phases.suppliers,
  project_phases.location,
  project_phases.weight,
  project_phases.order_index,
  project_phases.actual_duration
FROM btp.project_phases;

CREATE OR REPLACE VIEW public.projects AS
SELECT
  projects.id,
  projects.title,
  projects.description,
  projects.location,
  projects.status,
  projects.progress,
  projects.budget,
  projects.start_date,
  projects.end_date,
  projects.thumbnail,
  projects.team_size,
  projects.created_at,
  projects.updated_at,
  projects.coordinates_latitude,
  projects.coordinates_longitude,
  projects.project_order,
  projects.financing_source,
  projects.market_type,
  projects.selection_mode,
  projects.launch_date,
  projects.attribution_date,
  projects.completion_date,
  projects.project_reference,
  projects.project_responsable_id,
  projects.main_contractor,
  projects.allows_initial_payment,
  projects.initial_payment_percentage,
  projects.current_phase,
  projects.current_stage,
  projects.adresse,
  projects.forme,
  projects.localisation,
  projects.created_by,
  projects.check_schedule_last_run,
  projects.estimated_days,
  projects.project_reference_number,
  projects.currency,
  projects.payment_mode,
  projects.payment_frequency,
  projects.initial_advance_percentage,
  projects.retention_percentage,
  projects.priority,
  projects.project_type,
  projects.sector,
  projects.permit_number,
  projects.funding_source,
  projects.requires_consultant_validation,
  projects.requires_ministry_approval,
  projects.payment_workflow_config,
  projects.geographic_zone,
  projects.terrain_type,
  projects.environmental_constraints,
  projects.has_utilities,
  projects.requires_permits,
  projects.client_id,
  projects.engineering_consultant_id,
  projects.technical_manager_id,
  projects.supervisor_id,
  projects.workspace_id,
  projects.area_sqm,
  projects.site_details,
  projects.donor_organization,
  projects.bank_guarantee_required,
  projects.bank_guarantee_amount,
  projects.bank_guarantee_percentage,
  projects.insurance_required,
  projects.materials_budget,
  projects.procurement_lead_time,
  projects.resource_assignment,
  projects.reception_status,
  projects.closure_notes,
  projects.methodology,
  projects.referential_code
FROM btp.projects;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.projects TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.project_phases TO authenticated;
GRANT SELECT ON public.projects TO anon;
GRANT SELECT ON public.project_phases TO anon;
GRANT ALL ON public.projects TO service_role;
GRANT ALL ON public.project_phases TO service_role;