
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { requireSupabaseConfig } from '@/config/supabaseConfig';

/**
 * La résolution passe par SupabaseConfigService : il garantit que la clé
 * publiable appartient au même projet que l'URL (les clés héritées d'un autre
 * projet sont ignorées au lieu d'être utilisées).
 */
const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } = requireSupabaseConfig();


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Sérialise les opérations d'authentification dans cette instance de l'app.
 * Le LockManager natif échoue immédiatement dans certains navigateurs et
 * contextes embarqués. Une file de promesses conserve l'exclusion mutuelle
 * attendue par GoTrue sans dépendre de `navigator.locks`.
 */
const authLockQueues = new Map<string, Promise<void>>();

const tolerantLock = async <R>(name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> => {
  const previous = authLockQueues.get(name) ?? Promise.resolve();
  let release: (() => void) | undefined;
  const current = new Promise<void>((resolve) => {
    release = resolve;
  });
  const queued = previous.catch(() => undefined).then(() => current);
  authLockQueues.set(name, queued);

  await previous.catch(() => undefined);
  try {
    return await fn();
  } finally {
    release?.();
    if (authLockQueues.get(name) === queued) authLockQueues.delete(name);
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    lock: tolerantLock
  }
});

