
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

//const SUPABASE_URL = "https://huttgbybeuzeikaqfvam.supabase.co";
//const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1dHRnYnliZXV6ZWlrYXFmdmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjM3MzgsImV4cCI6MjA1ODgzOTczOH0.1VbV47UuczSyKrA_Rzxw2lywA25392bjNe6snuHVF0k";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const schemaProfileFetch: typeof fetch = async (input, init) => {
  const request = input instanceof Request ? input : new Request(input, init);
  const headers = new Headers(request.headers);
  const method = (request.method || init?.method || 'GET').toUpperCase();
  const acceptProfile = headers.get('Accept-Profile');

  if ((method === 'GET' || method === 'HEAD') && acceptProfile && acceptProfile !== 'public') {
    headers.set('Content-Profile', acceptProfile);
    headers.delete('Accept-Profile');
  }

  return fetch(new Request(request, { headers }));
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  },
  global: {
    fetch: schemaProfileFetch
  }
});
